// Created by Crowbar-Starfelll 1.0

$ModelName "survivors/test/survivor_Biker.mdl"

$SurfaceProp "flesh"

$Contents "solid"

$IllumPosition -2.397 0.123 38.156

$EyePosition 0 0 70

$MaxEyeDeflection 30

$ForcePhonemeCrossFade

$AmbientBoost

$MostlyOpaque

$CDMaterials "models\survivors\Biker\"
$CDMaterials "models\survivors\"
$CDMaterials ""

$TextureGroup "skinfamilies"
{
	{ "francis_head"    "francis_color"    }
	{ "francis_head_it" "francis_color_it" }
}

$Attachment "eyes" "ValveBiped.Bip01_Head1" 4.04 -2.79 0.06 rotate 0 -89.37 -90
$Attachment "mouth" "ValveBiped.Bip01_Head1" 0.84 -6.09 -0.16 rotate 0 -80 -90
$Attachment "pistol" "ValveBiped.Bip01_R_Thigh" -3.47 2.15 -5.69 rotate -3.66 -0.47 88.48
$Attachment "medkit" "ValveBiped.Bip01_Spine4" -1.34 -5.84 -1.37 rotate 5.03 77.16 0
$Attachment "primary" "ValveBiped.Bip01_Spine4" 3.21 -5.16 -2.75 rotate -13.7 170.19 174.29
$Attachment "attach_R_shoulderBladeAim" "ValveBiped.Bip01_Spine4" -11.07 -1.46 -5.33 rotate -90 -102.85 0
$Attachment "attach_L_shoulderBladeAim" "ValveBiped.Bip01_Spine4" -11.07 -1.46 3.69 rotate -90 -102.85 0
$Attachment "molotov" "ValveBiped.Bip01_Spine" -3.78 -2.89 8.29 rotate -63.44 -74.67 -101.41
$Attachment "grenade" "ValveBiped.Bip01_Spine" -0.8 1.38 9.33 rotate -90 -175.23 0
$Attachment "pills" "ValveBiped.Bip01_Spine" -3.1 0.74 -8.47 rotate -41.18 -88.48 -87.05
$Attachment "melee" "ValveBiped.Bip01_Spine4" 3.01 -5.84 5.74 rotate 24 175 97
$Attachment "grenade" "ValveBiped.Bip01_Spine" -0.8 1.38 9.33 rotate -90 -175.23 0
$Attachment "molotov" "ValveBiped.Bip01_Spine" -3.78 -2.89 8.29 rotate -63.44 -74.67 -101.41
$Attachment "pills" "ValveBiped.Bip01_Spine" -3.1 0.74 -8.47 rotate -41.18 -88.48 -87.05
$Attachment "medkit" "ValveBiped.Bip01_Spine4" -1.34 -5.84 -1.37 rotate 5.03 77.16 0
$Attachment "pistol" "ValveBiped.Bip01_R_Thigh" -3.47 2.15 -5.69 rotate -3.66 -0.47 88.48
$Attachment "primary" "ValveBiped.Bip01_Spine4" 3.21 -5.16 -2.75 rotate -13.7 170.19 174.29
$Attachment "eholster" "ValveBiped.Bip01_L_Thigh" 5.12 -2.21 5.1 rotate 9.47 -92.11 96.8
$Attachment "lfoot" "ValveBiped.Bip01_L_Foot" 0 5.25 0 rotate 0 0 0
$Attachment "rfoot" "ValveBiped.Bip01_R_Foot" 0 5.25 0 rotate 0 0 0
$Attachment "muzzle_flash" "ValveBiped.Bip01_L_Hand" 0 0 0 rotate 0 0 0
$Attachment "survivor_neck" "ValveBiped.Bip01_Neck1" 0 0 0 rotate 0 0 0
$Attachment "forward" "ValveBiped.forward" 0 0 0 rotate 0 0 0
$Attachment "bleedout" "ValveBiped.Bip01_Pelvis" 9.97 10.5 5.25 rotate 0 0 0
$Attachment "survivor_light" "ValveBiped.Bip01_Spine2" 6.3 25.2 0 rotate 0 0 0
$Attachment "legL_B" "ValveBiped.attachment_bandage_legL" 0 0 0 rotate -90 -90 0
$Attachment "armL_B" "ValveBiped.attachment_bandage_armL" 0 0 0 rotate -90 -90 0
$Attachment "armL_T" "ValveBiped.attachment_armL_T" 0 0 0 rotate -90 -90 0
$Attachment "armR_T" "ValveBiped.attachment_armR_T" 0 0 0 rotate -90 -90 0
$Attachment "armL" "ValveBiped.Bip01_L_Forearm" 0 0 0 rotate 0 0 0
$Attachment "legL" "ValveBiped.Bip01_L_Calf" 0 0 0 rotate 0 0 0
$Attachment "thighL" "ValveBiped.Bip01_L_Thigh" 0 0 0 rotate 0 0 0
$Attachment "spine" "ValveBiped.Bip01_Spine" 0 0 0 rotate -90 -90 0

$CBox 0 0 0 0 0 0

$BBox -13 -13 0 13 13 72

$HBoxSet "L4D"
$HBox 3 "ValveBiped.Bip01_Pelvis" -6.3 -4.725 -4.725 6.3 4.725 4.725
$HBox 6 "ValveBiped.Bip01_L_Thigh" 5.25 -3.57 -2.9925 19.949999 2.73 2.2575
$HBox 6 "ValveBiped.Bip01_L_Calf" 0.525 -2.1 -2.625 20.474998 3.15 2.625
$HBox 6 "ValveBiped.Bip01_L_Toe0" -3.675 -0.525 -1.4175 1.575 1.575 2.5725
$HBox 7 "ValveBiped.Bip01_R_Thigh" 5.25 -3.57 -2.9925 19.949999 2.73 2.2575
$HBox 7 "ValveBiped.Bip01_R_Calf" 0.525 -2.1 -2.625 20.474998 3.15 2.625
$HBox 7 "ValveBiped.Bip01_R_Toe0" -3.675 -0.525 -1.4175 1.575 1.575 2.5725
$HBox 3 "ValveBiped.Bip01_Spine1" -5.25 -4.4625 -6.3 5.25 6.5625 6.3
$HBox 2 "ValveBiped.Bip01_Spine2" -3.15 -3.57 -6.825 12.599999 6.929999 6.825
$HBox 1 "ValveBiped.Bip01_Neck1" 0 -2.625 -2.3625 4.2 2.625 2.3625
$HBox 1 "ValveBiped.Bip01_Head1" -0.84 -4.2 -3.2025 7.559999 4.2 2.5725
$HBox 4 "ValveBiped.Bip01_L_UpperArm" 0 -2.205 -2.1 11.549999 1.995 2.1
$HBox 4 "ValveBiped.Bip01_L_Forearm" 0.525 -1.8375 -1.8375 12.075 1.8375 1.8375
$HBox 4 "ValveBiped.Bip01_L_Hand" 1.113 -1.512 -2.52 5.838 0.588 1.365
$HBox 5 "ValveBiped.Bip01_R_UpperArm" 0 -2.205 -2.1 11.549999 1.995 2.1
$HBox 5 "ValveBiped.Bip01_R_Forearm" 0.525 -1.8375 -1.8375 12.075 1.8375 1.8375
$HBox 5 "ValveBiped.Bip01_R_Hand" 1.113 -1.512 -2.52 5.838 0.588 1.365
$SkipBoneInBBox

$DefineBone "ValveBiped.Bip01_Pelvis" "" 0 0.542612 40.233574 0 0 89.999975 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Thigh" "ValveBiped.Bip01_Pelvis" 3.806942 0 0 3.326308 -87.048507 -95.710935 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Calf" "ValveBiped.Bip01_L_Thigh" 19.263105 0 0 0 0 0 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Foot" "ValveBiped.Bip01_L_Calf" 17.5891 0 0 -3.939487 -74.439534 -4.413494 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Toe0" "ValveBiped.Bip01_L_Foot" 6.240662 0 0 -1.587609 -19.272641 1.162818 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Thigh" "ValveBiped.Bip01_Pelvis" -3.806942 0 0 3.326304 -92.951464 -84.289083 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Calf" "ValveBiped.Bip01_R_Thigh" 19.263098 0 0 0 0 0 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Foot" "ValveBiped.Bip01_R_Calf" 17.589096 0 0 3.939485 -74.439534 5.084026 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Toe0" "ValveBiped.Bip01_R_Foot" 6.240662 0 0 1.366218 -19.288965 -6.408019 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_Spine" "ValveBiped.Bip01_Pelvis" 0 4.246162 -0.018825 4.766603 89.999982 89.999982 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_Spine1" "ValveBiped.Bip01_Spine" 4.195629 0 0 0 -9.852982 0 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_Spine2" "ValveBiped.Bip01_Spine1" 3.883152 0.000001 0 0 -0.906993 0 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_Spine4" "ValveBiped.Bip01_Spine2" 5.985943 0.000002 0 0 28.371672 0 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_Neck1" "ValveBiped.Bip01_Spine4" 5.620499 0.000002 0 0 14.358378 179.999855 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_Head1" "ValveBiped.Bip01_Neck1" 4.684906 0.000002 0 -0.000057 26.575554 0 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Clavicle" "ValveBiped.Bip01_Spine4" 4.268658 1.531894 1.575 -73.220092 -107.221566 12.909378 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_UpperArm" "ValveBiped.Bip01_L_Clavicle" 5.782729 -0.000008 0.000001 -22.320309 -15.43947 -89.849294 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Forearm" "ValveBiped.Bip01_L_UpperArm" 11.452765 0.000001 -0.000004 -0.000003 -7.20247 0.000001 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Hand" "ValveBiped.Bip01_L_Forearm" 10.945532 -0.000006 -0.000031 6.507306 7.122675 78.669798 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Finger4" "ValveBiped.Bip01_L_Hand" 3.147137 0.005676 -1.551344 8.213351 -12.990152 11.742428 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Finger41" "ValveBiped.Bip01_L_Finger4" 1.585899 0 0 0.955234 -34.374607 0.653397 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Finger42" "ValveBiped.Bip01_L_Finger41" 0.849079 0 0 -10.048532 -17.354268 -3.121078 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Finger3" "ValveBiped.Bip01_L_Hand" 3.471083 0.213272 -0.574067 5.954124 -16.778206 11.337861 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Finger31" "ValveBiped.Bip01_L_Finger3" 1.897537 -0.000008 0 -5.063454 -30.512982 -2.977608 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Finger32" "ValveBiped.Bip01_L_Finger31" 1.01445 0.000004 0 0.559038 -13.904483 0.138366 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Finger2" "ValveBiped.Bip01_L_Hand" 3.750084 0.114773 0.430058 3.893595 -14.791072 10.7303 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Finger21" "ValveBiped.Bip01_L_Finger2" 2.258194 0 0 -3.092653 -37.967177 -2.410839 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Finger22" "ValveBiped.Bip01_L_Finger21" 1.210388 0.000008 0 0.688638 -8.970351 0.108686 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Finger1" "ValveBiped.Bip01_L_Hand" 3.868299 -0.166634 1.490139 1.961124 -11.693718 10.352716 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Finger11" "ValveBiped.Bip01_L_Finger1" 1.786062 0 0 3.66905 -38.756245 2.940814 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Finger12" "ValveBiped.Bip01_L_Finger11" 1.044445 -0.000004 0 2.209324 -1.89655 0.073161 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Finger0" "ValveBiped.Bip01_L_Hand" 1.121477 -1.351563 1.030997 -19.741822 -7.111202 97.051428 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Finger01" "ValveBiped.Bip01_L_Finger0" 1.928114 0 -0.000004 -10.778427 -10.616002 0.000002 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Finger02" "ValveBiped.Bip01_L_Finger01" 1.285139 0 0.000008 -2.32885 11.249045 -0.000001 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Clavicle" "ValveBiped.Bip01_Spine4" 4.268658 1.531896 -1.575 73.748558 -114.71968 -24.241033 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_UpperArm" "ValveBiped.Bip01_R_Clavicle" 5.782726 0 0 23.248945 -11.666445 95.170107 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Forearm" "ValveBiped.Bip01_R_UpperArm" 11.452768 -0.000001 0 0.000007 -7.202484 -0.000001 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Hand" "ValveBiped.Bip01_R_Forearm" 10.945511 -0.000005 0.000015 -6.507534 7.122605 -78.876985 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Finger4" "ValveBiped.Bip01_R_Hand" 3.147156 0.000069 1.551353 -8.213401 -12.98992 -11.535191 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Finger41" "ValveBiped.Bip01_R_Finger4" 1.585901 -0.000008 0 -0.955229 -34.374607 -0.653401 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Finger42" "ValveBiped.Bip01_R_Finger41" 0.849083 0.000004 0 10.048539 -17.354268 3.121073 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Finger3" "ValveBiped.Bip01_R_Hand" 3.471104 0.211185 0.574834 -5.954229 -16.777984 -11.130627 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Finger31" "ValveBiped.Bip01_R_Finger3" 1.897535 0 0 5.06346 -30.512989 2.977601 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Finger32" "ValveBiped.Bip01_R_Finger31" 1.014454 0 0 -0.559033 -13.904489 -0.138374 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Finger2" "ValveBiped.Bip01_R_Hand" 3.750103 0.116325 -0.42964 -3.8937 -14.79091 -10.523119 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Finger21" "ValveBiped.Bip01_R_Finger2" 2.258196 0.000008 0 3.092658 -37.967177 2.410831 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Finger22" "ValveBiped.Bip01_R_Finger21" 1.210384 0.000004 0 -0.688635 -8.970354 -0.108695 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Finger1" "ValveBiped.Bip01_R_Hand" 3.868322 -0.161243 -1.490732 -1.961171 -11.693492 -10.145484 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Finger11" "ValveBiped.Bip01_R_Finger1" 1.786062 -0.000008 0 -3.669044 -38.756256 -2.940823 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Finger12" "ValveBiped.Bip01_R_Finger11" 1.044445 0.000004 -0.000001 -2.209318 -1.896554 -0.073171 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Finger0" "ValveBiped.Bip01_R_Hand" 1.1215 -1.347832 -1.035882 19.767273 -7.037125 -96.83291 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Finger01" "ValveBiped.Bip01_R_Finger0" 1.92812 -0.000001 0 10.778424 -10.615989 -0.000001 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Finger02" "ValveBiped.Bip01_R_Finger01" 1.285143 0 0 2.32885 11.249053 0.000003 0 0 0 0 0 0
$DefineBone "ValveBiped.attachment_bandage_legL" "ValveBiped.Bip01_L_Calf" 7.023272 -6.880002 4.339547 -83.423261 -63.332738 150.153431 0 0 0 0 0 0
$DefineBone "ValveBiped.attachment_bandage_armL" "ValveBiped.Bip01_L_Forearm" 3.813803 -3.870654 0.998558 -61.28573 11.452962 89.999982 0 0 0 0 0 0
$DefineBone "ValveBiped.attachment_armL_T" "ValveBiped.Bip01_L_Forearm" 0 -0.000007 -0.000031 6.507306 7.122668 78.669798 0 0 0 0 0 0
$DefineBone "ValveBiped.attachment_armR_T" "ValveBiped.Bip01_R_Forearm" 0 -0.000007 -0.000034 6.507312 7.122668 78.669798 0 0 0 0 0 0
$DefineBone "ValveBiped.weapon_bone" "ValveBiped.Bip01_R_Hand" 2.856899 -1.536194 -0.9738 -15.61642 -90.427695 -86.009389 0 0 0 0 0 0
$DefineBone "ValveBiped.forward" "ValveBiped.Bip01_Head1" 2.000008 -3 0 0 -76 -90.000003 0 0 0 0 0 0
$DefineBone "ValveBiped.L_weapon_bone" "ValveBiped.Bip01_L_Hand" 3.349001 -1.370995 0.724999 -5.043001 89.255 113.321998 0 0 0 0 0 0
$DefineBone "ValveBiped.weapon_bone_Clip" "ValveBiped.weapon_bone" 0.000004 0 10.000004 0.000003 0.000002 0 0 0 0 0 0 0
$DefineBone "ValveBiped.weapon_bone_extra" "ValveBiped.weapon_bone" 0.018898 0.665158 9.395884 0.000003 0.000002 0 0 0 0 0 0 0
$DefineBone "ValveBiped.weapon_bone_Clip2" "ValveBiped.Bip01_L_Hand" 3.028212 -0.923409 -2.009451 -0.743371 90.942357 90.188249 0 0 0 0 0 0
$DefineBone "ValveBiped.weapon_bone_Clip2_Bullets" "ValveBiped.weapon_bone_Clip2" 0.116951 4.311603 0.061861 -0.000027 0.000011 0.000595 0 0 0 0 0 0
$DefineBone "ValveBiped.weapon_bolt_l" "ValveBiped.Bip01_L_Hand" 0 0 0 -0.000001 0.000003 0.000002 0 0 0 0 0 0
$DefineBone "ValveBiped.weapon_bone_Clip_Bullets" "ValveBiped.weapon_bone_Clip" 0 1 0.000008 0.000003 0.000002 0 0 0 0 0 0 0
$DefineBone "ValveBiped.weapon_bolt" "ValveBiped.weapon_bone" 0 0 0 0.000003 0.000002 0 0 0 0 0 0 0
$DefineBone "ValveBiped.weapon_bolt_opposite" "ValveBiped.weapon_bone" 0 0 0 0.000003 0.000002 0 0 0 0 0 0 0
$DefineBone "ValveBiped.weapon_charger" "ValveBiped.weapon_bone" 0 0 0 0.000003 0.000002 0 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Knee" "ValveBiped.Bip01_L_Thigh" 19.253853 0 -0.000001 0 1.446891 0.000001 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Knee" "ValveBiped.Bip01_R_Thigh" 19.253841 0 0 0.000001 1.446719 0 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Ulna" "ValveBiped.Bip01_L_Forearm" 5.884354 0 0.000004 -0.000002 -0.000001 -7.237037 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Wrist" "ValveBiped.Bip01_L_Forearm" 11.768705 -0.000001 0 -0.000002 -0.000001 -13.660905 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Elbow" "ValveBiped.Bip01_L_UpperArm" 11.679201 0 -0.000004 -0.000007 -9.262339 0 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Bicep" "ValveBiped.Bip01_L_UpperArm" 5.837998 -0.735 -0.525002 -0.000005 -0.000002 -0.000001 0 0 0 0 0 0
$DefineBone "ValveBiped.hlp_jacket_arm_front1_L" "ValveBiped.Bip01_L_Clavicle" 5.825531 2.661388 2.409388 -0.935077 -1.404084 -0.111467 0 0 0 0 0 0
$DefineBone "ValveBiped.hlp_jacket_arm_top_L" "ValveBiped.Bip01_L_Clavicle" 6.752561 4.039024 -0.341453 1.070353 -1.091604 0.082238 0 0 0 0 0 0
$DefineBone "ValveBiped.hlp_jacket_arm_back_L" "ValveBiped.Bip01_L_Clavicle" 7.652452 1.954227 -2.880674 0.67213 0.445368 1.964537 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Wrist" "ValveBiped.Bip01_R_Forearm" 11.768707 0.000001 0.000004 0.000005 0.000006 13.903744 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Ulna" "ValveBiped.Bip01_R_Forearm" 5.884352 0.000001 0 0.000005 0.000006 7.369187 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Elbow" "ValveBiped.Bip01_R_UpperArm" 11.679197 0 0.000008 0.000007 -9.26228 0 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Bicep" "ValveBiped.Bip01_R_UpperArm" 5.837997 -0.641044 0.525002 0.000009 0.000003 -2.835174 0 0 0 0 0 0
$DefineBone "ValveBiped.hlp_jacket_arm_front1_R" "ValveBiped.Bip01_R_Clavicle" 5.625286 3.107059 -2.433369 4.724489 -0.393593 6.351416 0 0 0 0 0 0
$DefineBone "ValveBiped.hlp_jacket_arm_top_R" "ValveBiped.Bip01_R_Clavicle" 6.677644 4.114117 0.449763 0.587011 -0.410608 -0.513601 0 0 0 0 0 0
$DefineBone "ValveBiped.hlp_jacket_arm_back_R" "ValveBiped.Bip01_R_Clavicle" 7.673524 1.768635 2.985535 0.372493 0.714035 -1.829523 0 0 0 0 0 0
$DefineBone "ValveBiped.hlp_jacket_armpit_R" "ValveBiped.Bip01_Spine2" 4.902687 0.655644 -8.954903 0.22288 0.009139 4.694948 0 0 0 0 0 0
$DefineBone "ValveBiped.jiggy_jacket_right" "ValveBiped.Bip01_Spine" 2.64967 8.412623 -3.003099 -63.666133 107.998289 -104.786583 0 0 0 0 0 0
$DefineBone "ValveBiped.jiggy_jacket_left" "ValveBiped.Bip01_Spine" 2.538502 8.321048 3.447679 -61.873939 -87.220498 88.028653 0 0 0 0 0 0

$BoneMerge "ValveBiped.Bip01_Pelvis"
$BoneMerge "ValveBiped.Bip01_Spine"
$BoneMerge "ValveBiped.Bip01_Spine1"
$BoneMerge "ValveBiped.Bip01_Spine2"
$BoneMerge "ValveBiped.Bip01_Spine4"
$BoneMerge "ValveBiped.Bip01_L_Clavicle"
$BoneMerge "ValveBiped.Bip01_L_UpperArm"
$BoneMerge "ValveBiped.Bip01_L_Forearm"
$BoneMerge "ValveBiped.Bip01_L_Hand"
$BoneMerge "ValveBiped.Bip01_L_Finger4"
$BoneMerge "ValveBiped.Bip01_L_Finger41"
$BoneMerge "ValveBiped.Bip01_L_Finger42"
$BoneMerge "ValveBiped.Bip01_L_Finger3"
$BoneMerge "ValveBiped.Bip01_L_Finger31"
$BoneMerge "ValveBiped.Bip01_L_Finger32"
$BoneMerge "ValveBiped.Bip01_L_Finger2"
$BoneMerge "ValveBiped.Bip01_L_Finger21"
$BoneMerge "ValveBiped.Bip01_L_Finger22"
$BoneMerge "ValveBiped.Bip01_L_Finger1"
$BoneMerge "ValveBiped.Bip01_L_Finger11"
$BoneMerge "ValveBiped.Bip01_L_Finger12"
$BoneMerge "ValveBiped.Bip01_L_Finger0"
$BoneMerge "ValveBiped.Bip01_L_Finger01"
$BoneMerge "ValveBiped.Bip01_L_Finger02"
$BoneMerge "ValveBiped.Bip01_R_Clavicle"
$BoneMerge "ValveBiped.Bip01_R_UpperArm"
$BoneMerge "ValveBiped.Bip01_R_Forearm"
$BoneMerge "ValveBiped.Bip01_R_Hand"
$BoneMerge "ValveBiped.Bip01_R_Finger4"
$BoneMerge "ValveBiped.Bip01_R_Finger41"
$BoneMerge "ValveBiped.Bip01_R_Finger42"
$BoneMerge "ValveBiped.Bip01_R_Finger3"
$BoneMerge "ValveBiped.Bip01_R_Finger31"
$BoneMerge "ValveBiped.Bip01_R_Finger32"
$BoneMerge "ValveBiped.Bip01_R_Finger2"
$BoneMerge "ValveBiped.Bip01_R_Finger21"
$BoneMerge "ValveBiped.Bip01_R_Finger22"
$BoneMerge "ValveBiped.Bip01_R_Finger1"
$BoneMerge "ValveBiped.Bip01_R_Finger11"
$BoneMerge "ValveBiped.Bip01_R_Finger12"
$BoneMerge "ValveBiped.Bip01_R_Finger0"
$BoneMerge "ValveBiped.Bip01_R_Finger01"
$BoneMerge "ValveBiped.Bip01_R_Finger02"
$BoneMerge "ValveBiped.weapon_bone"
$BoneMerge "ValveBiped.L_weapon_bone"
$BoneMerge "ValveBiped.weapon_bone_Clip"
$BoneMerge "ValveBiped.weapon_bone_extra"
$BoneMerge "ValveBiped.weapon_bone_Clip2"
$BoneMerge "ValveBiped.weapon_bone_Clip2_Bullets"
$BoneMerge "ValveBiped.weapon_bolt_l"
$BoneMerge "ValveBiped.weapon_bone_Clip_Bullets"
$BoneMerge "ValveBiped.weapon_bolt"
$BoneMerge "ValveBiped.weapon_bolt_opposite"
$BoneMerge "ValveBiped.weapon_charger"
$BoneMerge "ValveBiped.Bip01_L_Ulna"
$BoneMerge "ValveBiped.Bip01_L_Wrist"
$BoneMerge "ValveBiped.Bip01_R_Wrist"
$BoneMerge "ValveBiped.Bip01_R_Ulna"

$JiggleBone "ValveBiped.jiggy_jacket_right"
{
	is_flexible
	{
		length 20
		tip_mass 1000
		pitch_stiffness 100
		pitch_damping 7
		yaw_stiffness 100
		yaw_damping 7
		along_stiffness 100
		along_damping 0
		pitch_constraint -5 79.999998
		pitch_friction 0
		pitch_bounce 0
		yaw_constraint -30.000001 30.000001
		yaw_friction 0
		yaw_bounce 0
	}
}
$JiggleBone "ValveBiped.jiggy_jacket_left"
{
	is_flexible
	{
		length 20
		tip_mass 1000
		pitch_stiffness 100
		pitch_damping 7
		yaw_stiffness 100
		yaw_damping 7
		along_stiffness 100
		along_damping 0
		pitch_constraint -5 79.999998
		pitch_friction 0
		pitch_bounce 0
		yaw_constraint -30.000001 30.000001
		yaw_friction 0
		yaw_bounce 0
	}
}

$SectionFrames 30 168

$PoseParameter "body_pitch" -90 90 loop 360
$PoseParameter "body_yaw" -90 90 loop 360
$PoseParameter "head_pitch" -90 90 loop 360
$PoseParameter "head_yaw" -90 90 loop 360
$PoseParameter "move_y" -1 1 loop 0
$PoseParameter "move_x" -1 1 loop 0

$IKChain "rhand" "ValveBiped.Bip01_R_Hand" knee 0.707 0.707 0
$IKChain "lhand" "ValveBiped.Bip01_L_Hand" knee 0.707 0.707 0
$IKChain "rfoot" "ValveBiped.Bip01_R_Foot" knee 0.707 -0.707 0
$IKChain "lfoot" "ValveBiped.Bip01_L_Foot" knee 0.707 -0.707 0
$IKChain "ikclip" "ValveBiped.weapon_bone_Clip" knee 0.707 -0.707 0

$IKAutoPlayLock "rfoot" 1 0.1
$IKAutoPlayLock "lfoot" 1 0.1

$WeightList "weights_Idlenoise" {
	 "ValveBiped.Bip01_Pelvis" 0.4
	 "ValveBiped.Bip01_L_Thigh" 0
	 "ValveBiped.Bip01_L_Calf" 0
	 "ValveBiped.Bip01_L_Foot" 0
	 "ValveBiped.Bip01_L_Toe0" 0
	 "ValveBiped.Bip01_R_Thigh" 0
	 "ValveBiped.Bip01_R_Calf" 0
	 "ValveBiped.Bip01_R_Foot" 0
	 "ValveBiped.Bip01_R_Toe0" 0
	 "ValveBiped.Bip01_Spine" 0.2
	 "ValveBiped.Bip01_Spine1" 0.2
	 "ValveBiped.Bip01_Spine2" 0.2
	 "ValveBiped.Bip01_Spine4" 0.2
	 "ValveBiped.Bip01_Neck1" 0.2
	 "ValveBiped.Bip01_Head1" 0.2
	 "ValveBiped.Bip01_L_Clavicle" 0
	 "ValveBiped.Bip01_L_UpperArm" 0
	 "ValveBiped.Bip01_L_Forearm" 0
	 "ValveBiped.Bip01_L_Hand" 0
	 "ValveBiped.Bip01_L_Finger4" 0
	 "ValveBiped.Bip01_L_Finger41" 0
	 "ValveBiped.Bip01_L_Finger42" 0
	 "ValveBiped.Bip01_L_Finger3" 0
	 "ValveBiped.Bip01_L_Finger31" 0
	 "ValveBiped.Bip01_L_Finger32" 0
	 "ValveBiped.Bip01_L_Finger2" 0
	 "ValveBiped.Bip01_L_Finger21" 0
	 "ValveBiped.Bip01_L_Finger22" 0
	 "ValveBiped.Bip01_L_Finger1" 0
	 "ValveBiped.Bip01_L_Finger11" 0
	 "ValveBiped.Bip01_L_Finger12" 0
	 "ValveBiped.Bip01_L_Finger0" 0
	 "ValveBiped.Bip01_L_Finger01" 0
	 "ValveBiped.Bip01_L_Finger02" 0
	 "ValveBiped.Bip01_R_Clavicle" 0
	 "ValveBiped.Bip01_R_UpperArm" 0
	 "ValveBiped.Bip01_R_Forearm" 0
	 "ValveBiped.Bip01_R_Hand" 0
	 "ValveBiped.Bip01_R_Finger4" 0
	 "ValveBiped.Bip01_R_Finger41" 0
	 "ValveBiped.Bip01_R_Finger42" 0
	 "ValveBiped.Bip01_R_Finger3" 0
	 "ValveBiped.Bip01_R_Finger31" 0
	 "ValveBiped.Bip01_R_Finger32" 0
	 "ValveBiped.Bip01_R_Finger2" 0
	 "ValveBiped.Bip01_R_Finger21" 0
	 "ValveBiped.Bip01_R_Finger22" 0
	 "ValveBiped.Bip01_R_Finger1" 0
	 "ValveBiped.Bip01_R_Finger11" 0
	 "ValveBiped.Bip01_R_Finger12" 0
	 "ValveBiped.Bip01_R_Finger0" 0
	 "ValveBiped.Bip01_R_Finger01" 0
	 "ValveBiped.Bip01_R_Finger02" 0
	 "ValveBiped.attachment_bandage_legL" 0
	 "ValveBiped.attachment_bandage_armL" 0
	 "ValveBiped.attachment_armL_T" 0
	 "ValveBiped.attachment_armR_T" 0
	 "ValveBiped.weapon_bone" 0
	 "ValveBiped.forward" 0.2
	 "ValveBiped.L_weapon_bone" 0
	 "ValveBiped.weapon_bone_Clip" 0
	 "ValveBiped.weapon_bone_extra" 0
	 "ValveBiped.weapon_bone_Clip2" 0
	 "ValveBiped.weapon_bone_Clip2_Bullets" 0
	 "ValveBiped.weapon_bolt_l" 0
	 "ValveBiped.weapon_bone_Clip_Bullets" 0
	 "ValveBiped.weapon_bolt" 0
	 "ValveBiped.weapon_bolt_opposite" 0
	 "ValveBiped.weapon_charger" 0
	 "ValveBiped.Bip01_L_Knee" 0
	 "ValveBiped.Bip01_R_Knee" 0
	 "ValveBiped.Bip01_L_Ulna" 0
	 "ValveBiped.Bip01_L_Wrist" 0
	 "ValveBiped.Bip01_L_Elbow" 0
	 "ValveBiped.Bip01_L_Bicep" 0
	 "ValveBiped.hlp_jacket_arm_front1_L" 0
	 "ValveBiped.hlp_jacket_arm_top_L" 0
	 "ValveBiped.hlp_jacket_arm_back_L" 0
	 "ValveBiped.Bip01_R_Wrist" 0
	 "ValveBiped.Bip01_R_Ulna" 0
	 "ValveBiped.Bip01_R_Elbow" 0
	 "ValveBiped.Bip01_R_Bicep" 0
	 "ValveBiped.hlp_jacket_arm_front1_R" 0
	 "ValveBiped.hlp_jacket_arm_top_R" 0
	 "ValveBiped.hlp_jacket_arm_back_R" 0
	 "ValveBiped.hlp_jacket_armpit_R" 0.2
	 "ValveBiped.jiggy_jacket_right" 0.2
	 "ValveBiped.jiggy_jacket_left" 0.2
}

$WeightList "weights_InjuredIdlenoise" {
	 "ValveBiped.Bip01_Pelvis" 0
	 "ValveBiped.Bip01_L_Thigh" 0
	 "ValveBiped.Bip01_L_Calf" 0
	 "ValveBiped.Bip01_L_Foot" 0
	 "ValveBiped.Bip01_L_Toe0" 0
	 "ValveBiped.Bip01_R_Thigh" 0
	 "ValveBiped.Bip01_R_Calf" 0
	 "ValveBiped.Bip01_R_Foot" 0
	 "ValveBiped.Bip01_R_Toe0" 0
	 "ValveBiped.Bip01_Spine" 0
	 "ValveBiped.Bip01_Spine1" 0
	 "ValveBiped.Bip01_Spine2" 0
	 "ValveBiped.Bip01_Spine4" 0
	 "ValveBiped.Bip01_Neck1" 0
	 "ValveBiped.Bip01_Head1" 0
	 "ValveBiped.Bip01_L_Clavicle" 0
	 "ValveBiped.Bip01_L_UpperArm" 0
	 "ValveBiped.Bip01_L_Forearm" 0
	 "ValveBiped.Bip01_L_Hand" 0
	 "ValveBiped.Bip01_L_Finger4" 0
	 "ValveBiped.Bip01_L_Finger41" 0
	 "ValveBiped.Bip01_L_Finger42" 0
	 "ValveBiped.Bip01_L_Finger3" 0
	 "ValveBiped.Bip01_L_Finger31" 0
	 "ValveBiped.Bip01_L_Finger32" 0
	 "ValveBiped.Bip01_L_Finger2" 0
	 "ValveBiped.Bip01_L_Finger21" 0
	 "ValveBiped.Bip01_L_Finger22" 0
	 "ValveBiped.Bip01_L_Finger1" 0
	 "ValveBiped.Bip01_L_Finger11" 0
	 "ValveBiped.Bip01_L_Finger12" 0
	 "ValveBiped.Bip01_L_Finger0" 0
	 "ValveBiped.Bip01_L_Finger01" 0
	 "ValveBiped.Bip01_L_Finger02" 0
	 "ValveBiped.Bip01_R_Clavicle" 0
	 "ValveBiped.Bip01_R_UpperArm" 0
	 "ValveBiped.Bip01_R_Forearm" 0
	 "ValveBiped.Bip01_R_Hand" 0
	 "ValveBiped.Bip01_R_Finger4" 0
	 "ValveBiped.Bip01_R_Finger41" 0
	 "ValveBiped.Bip01_R_Finger42" 0
	 "ValveBiped.Bip01_R_Finger3" 0
	 "ValveBiped.Bip01_R_Finger31" 0
	 "ValveBiped.Bip01_R_Finger32" 0
	 "ValveBiped.Bip01_R_Finger2" 0
	 "ValveBiped.Bip01_R_Finger21" 0
	 "ValveBiped.Bip01_R_Finger22" 0
	 "ValveBiped.Bip01_R_Finger1" 0
	 "ValveBiped.Bip01_R_Finger11" 0
	 "ValveBiped.Bip01_R_Finger12" 0
	 "ValveBiped.Bip01_R_Finger0" 0
	 "ValveBiped.Bip01_R_Finger01" 0
	 "ValveBiped.Bip01_R_Finger02" 0
	 "ValveBiped.attachment_bandage_legL" 0
	 "ValveBiped.attachment_bandage_armL" 0
	 "ValveBiped.attachment_armL_T" 0
	 "ValveBiped.attachment_armR_T" 0
	 "ValveBiped.weapon_bone" 0
	 "ValveBiped.forward" 0
	 "ValveBiped.L_weapon_bone" 0
	 "ValveBiped.weapon_bone_Clip" 0
	 "ValveBiped.weapon_bone_extra" 0
	 "ValveBiped.weapon_bone_Clip2" 0
	 "ValveBiped.weapon_bone_Clip2_Bullets" 0
	 "ValveBiped.weapon_bolt_l" 0
	 "ValveBiped.weapon_bone_Clip_Bullets" 0
	 "ValveBiped.weapon_bolt" 0
	 "ValveBiped.weapon_bolt_opposite" 0
	 "ValveBiped.weapon_charger" 0
	 "ValveBiped.Bip01_L_Knee" 0
	 "ValveBiped.Bip01_R_Knee" 0
	 "ValveBiped.Bip01_L_Ulna" 0
	 "ValveBiped.Bip01_L_Wrist" 0
	 "ValveBiped.Bip01_L_Elbow" 0
	 "ValveBiped.Bip01_L_Bicep" 0
	 "ValveBiped.hlp_jacket_arm_front1_L" 0
	 "ValveBiped.hlp_jacket_arm_top_L" 0
	 "ValveBiped.hlp_jacket_arm_back_L" 0
	 "ValveBiped.Bip01_R_Wrist" 0
	 "ValveBiped.Bip01_R_Ulna" 0
	 "ValveBiped.Bip01_R_Elbow" 0
	 "ValveBiped.Bip01_R_Bicep" 0
	 "ValveBiped.hlp_jacket_arm_front1_R" 0
	 "ValveBiped.hlp_jacket_arm_top_R" 0
	 "ValveBiped.hlp_jacket_arm_back_R" 0
	 "ValveBiped.hlp_jacket_armpit_R" 0
	 "ValveBiped.jiggy_jacket_right" 0
	 "ValveBiped.jiggy_jacket_left" 0
}

$Animation "@Idlenoise_corrective_animation" "survivor_biker_anims\@Idlenoise_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_Walking_straight_up_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Walking_straight_up_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_Walking_up_right_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Walking_up_right_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_Walking_up_center_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Walking_up_center_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_Walking_up_left_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Walking_up_left_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_Walking_mid_right_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Walking_mid_right_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_Walking_mid_center_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Walking_mid_center_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_Walking_mid_left_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Walking_mid_left_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_Walking_down_right_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Walking_down_right_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_Walking_down_center_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Walking_down_center_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_Walking_down_left_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Walking_down_left_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_CrouchWalking_straight_up_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_CrouchWalking_straight_up_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_CrouchWalking_up_right_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_CrouchWalking_up_right_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_CrouchWalking_up_center_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_CrouchWalking_up_center_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_CrouchWalking_up_left_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_CrouchWalking_up_left_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_CrouchWalking_mid_right_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_CrouchWalking_mid_right_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_CrouchWalking_mid_center_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_CrouchWalking_mid_center_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_CrouchWalking_mid_left_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_CrouchWalking_mid_left_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_CrouchWalking_down_right_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_CrouchWalking_down_right_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_CrouchWalking_down_center_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_CrouchWalking_down_center_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_CrouchWalking_down_left_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_CrouchWalking_down_left_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_Standing_Calm_straight_up_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Standing_Calm_straight_up_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_Standing_Calm_up_right_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Standing_Calm_up_right_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_Standing_Calm_up_center_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Standing_Calm_up_center_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_Standing_Calm_up_left_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Standing_Calm_up_left_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_Standing_Calm_mid_right_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Standing_Calm_mid_right_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_Standing_Calm_mid_center_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Standing_Calm_mid_center_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_Standing_Calm_mid_left_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Standing_Calm_mid_left_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_Standing_Calm_down_right_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Standing_Calm_down_right_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_Standing_Calm_down_center_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Standing_Calm_down_center_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_Standing_Calm_down_left_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Standing_Calm_down_left_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_Standing_straight_up_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Standing_straight_up_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_Standing_up_right_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Standing_up_right_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_Standing_up_center_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Standing_up_center_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_Standing_up_left_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Standing_up_left_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_Standing_mid_right_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Standing_mid_right_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_Standing_mid_center_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Standing_mid_center_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_Standing_mid_left_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Standing_mid_left_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_Standing_down_right_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Standing_down_right_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_Standing_down_center_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Standing_down_center_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_Standing_down_left_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Standing_down_left_corrective_animation.smd" {
}

$Animation "a_francis_AimMatrix_Rifle_Running_straight_up_corrective_animation" "survivor_biker_anims\a_francis_AimMatrix_Rifle_Running_straight_up_corrective_animation.smd" {
}

$Animation "a_francis_AimMatrix_Rifle_Running_up_right_corrective_animation" "survivor_biker_anims\a_francis_AimMatrix_Rifle_Running_up_right_corrective_animation.smd" {
}

$Animation "a_francis_AimMatrix_Rifle_Running_up_center_corrective_animation" "survivor_biker_anims\a_francis_AimMatrix_Rifle_Running_up_center_corrective_animation.smd" {
}

$Animation "a_francis_AimMatrix_Rifle_Running_up_left_corrective_animation" "survivor_biker_anims\a_francis_AimMatrix_Rifle_Running_up_left_corrective_animation.smd" {
}

$Animation "a_francis_AimMatrix_Rifle_Running_mid_right_corrective_animation" "survivor_biker_anims\a_francis_AimMatrix_Rifle_Running_mid_right_corrective_animation.smd" {
}

$Animation "a_francis_AimMatrix_Rifle_Running_mid_center_corrective_animation" "survivor_biker_anims\a_francis_AimMatrix_Rifle_Running_mid_center_corrective_animation.smd" {
}

$Animation "a_francis_AimMatrix_Rifle_Running_mid_left_corrective_animation" "survivor_biker_anims\a_francis_AimMatrix_Rifle_Running_mid_left_corrective_animation.smd" {
}

$Animation "a_francis_AimMatrix_Rifle_Running_down_right_corrective_animation" "survivor_biker_anims\a_francis_AimMatrix_Rifle_Running_down_right_corrective_animation.smd" {
}

$Animation "a_francis_AimMatrix_Rifle_Running_down_center_corrective_animation" "survivor_biker_anims\a_francis_AimMatrix_Rifle_Running_down_center_corrective_animation.smd" {
}

$Animation "a_francis_AimMatrix_Rifle_Running_down_left_corrective_animation" "survivor_biker_anims\a_francis_AimMatrix_Rifle_Running_down_left_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_Crouching_straight_up_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Crouching_straight_up_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_Crouching_up_right_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Crouching_up_right_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_Crouching_up_center_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Crouching_up_center_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_Crouching_up_left_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Crouching_up_left_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_Crouching_mid_right_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Crouching_mid_right_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_Crouching_mid_center_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Crouching_mid_center_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_Crouching_mid_left_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Crouching_mid_left_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_Crouching_down_right_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Crouching_down_right_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_Crouching_down_center_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Crouching_down_center_corrective_animation.smd" {
}

$Animation "a_NamVet_AimMatrix_Rifle_Crouching_down_left_corrective_animation" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Crouching_down_left_corrective_animation.smd" {
}

$Animation "a_namvet_walkN_rifle" "survivor_biker_anims\a_namvet_walkN_rifle.smd" {
	fps 30
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 58 58 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 58 58 target 1
	ikrule "rfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 58 58 target 2
	ikrule "lfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 58 58 target 3
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 58 58 target 4
}

$Animation "a_namvet_runN_rifle" "survivor_biker_anims\a_namvet_runN_rifle.smd" {
	fps 30
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 41 41 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 41 41 target 1
	ikrule "rfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 41 41 target 2
	ikrule "lfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 41 41 target 3
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 41 41 target 4
}

$Animation "a_namvet_crouchWalkN_rifle" "survivor_biker_anims\a_namvet_crouchWalkN_rifle.smd" {
	fps 30
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 60 60 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 60 60 target 1
	ikrule "rfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 60 60 target 2
	ikrule "lfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 60 60 target 3
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 60 60 target 4
}

$Animation "a_namvet_limprunN_rifle" "survivor_biker_anims\a_namvet_limprunN_rifle.smd" {
	fps 30
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 34 34 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 34 34 target 1
	ikrule "rfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 34 34 target 2
	ikrule "lfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 34 34 target 3
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 34 34 target 4
}

$Animation "a_francis_AimMatrix_Rifle_Standing" "survivor_biker_anims\a_francis_AimMatrix_Rifle_Standing.smd" {
	fps 40
	loop
	ikrule "lfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 241 241 target 3
	ikrule "rfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 241 241 target 2
	ikrule "lhand" touch "ValveBiped.Bip01_R_Hand" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 241 241 target 1
}

$Animation "a_NamVet_AimMatrix_Rifle_Walking_neutral" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Walking_neutral.smd" {
	fps 30
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 1
	ikrule "rfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 2
	ikrule "lfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 3
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 4
}

$Animation "a_NamVet_AimMatrix_Rifle_Walking_down_right" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Walking_down_right.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_Walking_down_right_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_Walking_down_center" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Walking_down_center.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_Walking_down_center_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_Walking_down_left" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Walking_down_left.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_Walking_down_left_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_Walking_mid_right" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Walking_mid_right.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_Walking_mid_right_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_Walking_mid_center" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Walking_mid_center.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_Walking_mid_center_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_Walking_mid_left" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Walking_mid_left.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_Walking_mid_left_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_Walking_up_right" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Walking_up_right.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_Walking_up_right_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_Walking_up_center" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Walking_up_center.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_Walking_up_center_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_Walking_up_left" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Walking_up_left.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_Walking_up_left_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_Walking_straight_up" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Walking_straight_up.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_Walking_straight_up_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_CrouchWalking_neutral" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_CrouchWalking_neutral.smd" {
	fps 30
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 1
	ikrule "rfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 2
	ikrule "lfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 3
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 4
}

$Animation "a_NamVet_AimMatrix_Rifle_CrouchWalking_down_right" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_CrouchWalking_down_right.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_CrouchWalking_down_right_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_CrouchWalking_down_center" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_CrouchWalking_down_center.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_CrouchWalking_down_center_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_CrouchWalking_down_left" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_CrouchWalking_down_left.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_CrouchWalking_down_left_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_CrouchWalking_mid_right" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_CrouchWalking_mid_right.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_CrouchWalking_mid_right_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_CrouchWalking_mid_center" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_CrouchWalking_mid_center.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_CrouchWalking_mid_center_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_CrouchWalking_mid_left" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_CrouchWalking_mid_left.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_CrouchWalking_mid_left_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_CrouchWalking_up_right" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_CrouchWalking_up_right.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_CrouchWalking_up_right_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_CrouchWalking_up_center" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_CrouchWalking_up_center.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_CrouchWalking_up_center_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_CrouchWalking_up_left" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_CrouchWalking_up_left.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_CrouchWalking_up_left_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_CrouchWalking_straight_up" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_CrouchWalking_straight_up.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_CrouchWalking_straight_up_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_Standing_Calm_neutral" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Standing_Calm_neutral.smd" {
	fps 30
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 1
	ikrule "rfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 2
	ikrule "lfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 3
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 4
}

$Animation "a_NamVet_AimMatrix_Rifle_Standing_Calm_down_right" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Standing_Calm_down_right.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_Standing_Calm_down_right_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_Standing_Calm_down_center" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Standing_Calm_down_center.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_Standing_Calm_down_center_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_Standing_Calm_down_left" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Standing_Calm_down_left.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_Standing_Calm_down_left_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_Standing_Calm_mid_right" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Standing_Calm_mid_right.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_Standing_Calm_mid_right_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_Standing_Calm_mid_center" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Standing_Calm_mid_center.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_Standing_Calm_mid_center_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_Standing_Calm_mid_left" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Standing_Calm_mid_left.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_Standing_Calm_mid_left_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_Standing_Calm_up_right" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Standing_Calm_up_right.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_Standing_Calm_up_right_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_Standing_Calm_up_center" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Standing_Calm_up_center.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_Standing_Calm_up_center_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_Standing_Calm_up_left" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Standing_Calm_up_left.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_Standing_Calm_up_left_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_Standing_Calm_straight_up" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Standing_Calm_straight_up.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_Standing_Calm_straight_up_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_Standing_neutral" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Standing_neutral.smd" {
	fps 30
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 1
	ikrule "rfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 2
	ikrule "lfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 3
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 4
}

$Animation "a_NamVet_AimMatrix_Rifle_Standing_down_right" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Standing_down_right.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_Standing_down_right_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_Standing_down_center" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Standing_down_center.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_Standing_down_center_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_Standing_down_left" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Standing_down_left.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_Standing_down_left_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_Standing_mid_right" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Standing_mid_right.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_Standing_mid_right_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_Standing_mid_center" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Standing_mid_center.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_Standing_mid_center_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_Standing_mid_left" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Standing_mid_left.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_Standing_mid_left_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_Standing_up_right" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Standing_up_right.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_Standing_up_right_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_Standing_up_center" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Standing_up_center.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_Standing_up_center_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_Standing_up_left" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Standing_up_left.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_Standing_up_left_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_Standing_straight_up" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Standing_straight_up.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_Standing_straight_up_corrective_animation" 0
}

$Animation "a_francis_AimMatrix_Rifle_Running_neutral" "survivor_biker_anims\a_francis_AimMatrix_Rifle_Running_neutral.smd" {
	fps 30
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 1
	ikrule "rfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 2
	ikrule "lfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 3
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 4
}

$Animation "a_francis_AimMatrix_Rifle_Running_down_right" "survivor_biker_anims\a_francis_AimMatrix_Rifle_Running_down_right.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_francis_AimMatrix_Rifle_Running_down_right_corrective_animation" 0
}

$Animation "a_francis_AimMatrix_Rifle_Running_down_center" "survivor_biker_anims\a_francis_AimMatrix_Rifle_Running_down_center.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_francis_AimMatrix_Rifle_Running_down_center_corrective_animation" 0
}

$Animation "a_francis_AimMatrix_Rifle_Running_down_left" "survivor_biker_anims\a_francis_AimMatrix_Rifle_Running_down_left.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_francis_AimMatrix_Rifle_Running_down_left_corrective_animation" 0
}

$Animation "a_francis_AimMatrix_Rifle_Running_mid_right" "survivor_biker_anims\a_francis_AimMatrix_Rifle_Running_mid_right.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_francis_AimMatrix_Rifle_Running_mid_right_corrective_animation" 0
}

$Animation "a_francis_AimMatrix_Rifle_Running_mid_center" "survivor_biker_anims\a_francis_AimMatrix_Rifle_Running_mid_center.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_francis_AimMatrix_Rifle_Running_mid_center_corrective_animation" 0
}

$Animation "a_francis_AimMatrix_Rifle_Running_mid_left" "survivor_biker_anims\a_francis_AimMatrix_Rifle_Running_mid_left.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_francis_AimMatrix_Rifle_Running_mid_left_corrective_animation" 0
}

$Animation "a_francis_AimMatrix_Rifle_Running_up_right" "survivor_biker_anims\a_francis_AimMatrix_Rifle_Running_up_right.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_francis_AimMatrix_Rifle_Running_up_right_corrective_animation" 0
}

$Animation "a_francis_AimMatrix_Rifle_Running_up_center" "survivor_biker_anims\a_francis_AimMatrix_Rifle_Running_up_center.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_francis_AimMatrix_Rifle_Running_up_center_corrective_animation" 0
}

$Animation "a_francis_AimMatrix_Rifle_Running_up_left" "survivor_biker_anims\a_francis_AimMatrix_Rifle_Running_up_left.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_francis_AimMatrix_Rifle_Running_up_left_corrective_animation" 0
}

$Animation "a_francis_AimMatrix_Rifle_Running_straight_up" "survivor_biker_anims\a_francis_AimMatrix_Rifle_Running_straight_up.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_francis_AimMatrix_Rifle_Running_straight_up_corrective_animation" 0
}

$Animation "a_Run_RifleN" "survivor_biker_anims\a_Run_RifleN.smd" {
	fps 30.9
	loop
	ikrule "lhand" touch "ValveBiped.Bip01_R_Hand" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 40 40 target 1
	ikrule "lfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 40 40 target 3
	ikrule "rfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 40 40 target 2
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 40 40 target 0
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 40 40 target 4
	walkframe 40 LX LY
}

$Animation "a_Run_RifleS" "survivor_biker_anims\a_Run_RifleS.smd" {
	fps 30.9
	loop
	ikrule "lhand" touch "ValveBiped.Bip01_R_Hand" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 38 38 target 1
	ikrule "lfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 38 38 target 3
	ikrule "rfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 38 38 target 2
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 38 38 target 0
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 38 38 target 4
	walkframe 38 LX LY
}

$Animation "a_Run_RifleSE" "survivor_biker_anims\a_Run_RifleSE.smd" {
	fps 30.9
	loop
	ikrule "lhand" touch "ValveBiped.Bip01_R_Hand" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 38 38 target 1
	ikrule "lfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 38 38 target 3
	ikrule "rfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 38 38 target 2
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 38 38 target 0
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 38 38 target 4
	walkframe 38 LX LY
}

$Animation "a_Run_RifleE" "survivor_biker_anims\a_Run_RifleE.smd" {
	fps 30.9
	loop
	ikrule "lhand" touch "ValveBiped.Bip01_R_Hand" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 40 40 target 1
	ikrule "lfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 40 40 target 3
	ikrule "rfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 40 40 target 2
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 40 40 target 0
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 40 40 target 4
	walkframe 40 LX LY
}

$Animation "a_Run_RifleNE" "survivor_biker_anims\a_Run_RifleNE.smd" {
	fps 30.9
	loop
	ikrule "lhand" touch "ValveBiped.Bip01_R_Hand" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 40 40 target 1
	ikrule "lfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 40 40 target 3
	ikrule "rfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 40 40 target 2
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 40 40 target 0
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 40 40 target 4
	walkframe 40 LX LY
}

$Animation "a_Run_RifleNW" "survivor_biker_anims\a_Run_RifleNW.smd" {
	fps 30.9
	loop
	ikrule "lhand" touch "ValveBiped.Bip01_R_Hand" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 40 40 target 1
	ikrule "lfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 40 40 target 3
	ikrule "rfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 40 40 target 2
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 40 40 target 0
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 40 40 target 4
	walkframe 40 LX LY
}

$Animation "a_Run_RifleW" "survivor_biker_anims\a_Run_RifleW.smd" {
	fps 30.9
	loop
	ikrule "lhand" touch "ValveBiped.Bip01_R_Hand" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 40 40 target 1
	ikrule "lfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 40 40 target 3
	ikrule "rfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 40 40 target 2
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 40 40 target 0
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 40 40 target 4
	walkframe 40 LX LY
}

$Animation "a_Run_RifleSW" "survivor_biker_anims\a_Run_RifleSW.smd" {
	fps 30.9
	loop
	ikrule "lhand" touch "ValveBiped.Bip01_R_Hand" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 38 38 target 1
	ikrule "lfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 38 38 target 3
	ikrule "rfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 38 38 target 2
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 38 38 target 0
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 38 38 target 4
	walkframe 38 LX LY
}

$Animation "a_Run_RifleZero" "survivor_biker_anims\a_Run_RifleZero.smd" {
	fps 30
	loop
	ikrule "lhand" touch "ValveBiped.Bip01_R_Hand" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 99 99 target 1
	ikrule "lfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 99 99 target 3
	ikrule "rfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 99 99 target 2
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 99 99 target 0
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 99 99 target 4
}

$Animation "a_francis_AimMatrix_Rifle_Crouching" "survivor_biker_anims\a_francis_AimMatrix_Rifle_Crouching.smd" {
	fps 40
	loop
	ikrule "lfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 241 241 target 3
	ikrule "rfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 241 241 target 2
	ikrule "lhand" touch "ValveBiped.Bip01_R_Hand" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 241 241 target 1
}

$Animation "a_Walk_RifleN" "survivor_biker_anims\a_Walk_RifleN.smd" {
	fps 30
	loop
	ikrule "lhand" touch "ValveBiped.Bip01_R_Hand" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 58 58 target 1
	ikrule "lfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 58 58 target 3
	ikrule "rfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 58 58 target 2
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 58 58 target 0
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 58 58 target 4
	walkframe 58 LX LY
}

$Animation "a_Walk_RifleS" "survivor_biker_anims\a_Walk_RifleS.smd" {
	fps 30
	loop
	ikrule "lhand" touch "ValveBiped.Bip01_R_Hand" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 56 56 target 1
	ikrule "lfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 56 56 target 3
	ikrule "rfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 56 56 target 2
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 56 56 target 0
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 56 56 target 4
	walkframe 56 LX LY
}

$Animation "a_Walk_RifleSE" "survivor_biker_anims\a_Walk_RifleSE.smd" {
	fps 30
	loop
	ikrule "lhand" touch "ValveBiped.Bip01_R_Hand" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 56 56 target 1
	ikrule "lfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 56 56 target 3
	ikrule "rfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 56 56 target 2
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 56 56 target 0
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 56 56 target 4
	walkframe 56 LX LY
}

$Animation "a_Walk_RifleE" "survivor_biker_anims\a_Walk_RifleE.smd" {
	fps 30
	loop
	ikrule "lhand" touch "ValveBiped.Bip01_R_Hand" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 58 58 target 1
	ikrule "lfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 58 58 target 3
	ikrule "rfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 58 58 target 2
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 58 58 target 0
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 58 58 target 4
	walkframe 58 LX LY
}

$Animation "a_Walk_RifleNE" "survivor_biker_anims\a_Walk_RifleNE.smd" {
	fps 30
	loop
	ikrule "lhand" touch "ValveBiped.Bip01_R_Hand" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 58 58 target 1
	ikrule "lfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 58 58 target 3
	ikrule "rfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 58 58 target 2
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 58 58 target 0
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 58 58 target 4
	walkframe 58 LX LY
}

$Animation "a_Walk_RifleNW" "survivor_biker_anims\a_Walk_RifleNW.smd" {
	fps 30
	loop
	ikrule "lhand" touch "ValveBiped.Bip01_R_Hand" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 58 58 target 1
	ikrule "lfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 58 58 target 3
	ikrule "rfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 58 58 target 2
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 58 58 target 0
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 58 58 target 4
	walkframe 58 LX LY
}

$Animation "a_Walk_RifleW" "survivor_biker_anims\a_Walk_RifleW.smd" {
	fps 30
	loop
	ikrule "lhand" touch "ValveBiped.Bip01_R_Hand" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 58 58 target 1
	ikrule "lfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 58 58 target 3
	ikrule "rfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 58 58 target 2
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 58 58 target 0
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 58 58 target 4
	walkframe 58 LX LY
}

$Animation "a_Walk_RifleSW" "survivor_biker_anims\a_Walk_RifleSW.smd" {
	fps 30
	loop
	ikrule "lhand" touch "ValveBiped.Bip01_R_Hand" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 56 56 target 1
	ikrule "lfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 56 56 target 3
	ikrule "rfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 56 56 target 2
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 56 56 target 0
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 56 56 target 4
	walkframe 56 LX LY
}

$Animation "a_Walk_RifleZero" "survivor_biker_anims\a_Walk_RifleZero.smd" {
	fps 30
	loop
	ikrule "lhand" touch "ValveBiped.Bip01_R_Hand" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 99 99 target 1
	ikrule "lfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 99 99 target 3
	ikrule "rfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 99 99 target 2
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 99 99 target 0
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 99 99 target 4
}

$Animation "a_CrouchWalk_RifleN" "survivor_biker_anims\a_CrouchWalk_RifleN.smd" {
	fps 25.05
	loop
	ikrule "lhand" touch "ValveBiped.Bip01_R_Hand" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 55 55 target 1
	ikrule "lfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 55 55 target 3
	ikrule "rfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 55 55 target 2
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 55 55 target 0
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 55 55 target 4
	walkframe 55 LX LY
}

$Animation "a_CrouchWalk_RifleS" "survivor_biker_anims\a_CrouchWalk_RifleS.smd" {
	fps 24.96
	loop
	ikrule "lhand" touch "ValveBiped.Bip01_R_Hand" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 49 49 target 1
	ikrule "lfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 49 49 target 3
	ikrule "rfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 49 49 target 2
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 49 49 target 0
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 49 49 target 4
	walkframe 49 LX LY
}

$Animation "a_CrouchWalk_RifleSE" "survivor_biker_anims\a_CrouchWalk_RifleSE.smd" {
	fps 24.96
	loop
	ikrule "lhand" touch "ValveBiped.Bip01_R_Hand" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 49 49 target 1
	ikrule "lfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 49 49 target 3
	ikrule "rfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 49 49 target 2
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 49 49 target 0
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 49 49 target 4
	walkframe 49 LX LY
}

$Animation "a_CrouchWalk_RifleE" "survivor_biker_anims\a_CrouchWalk_RifleE.smd" {
	fps 27.4
	loop
	ikrule "lhand" touch "ValveBiped.Bip01_R_Hand" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 55 55 target 1
	ikrule "lfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 55 55 target 3
	ikrule "rfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 55 55 target 2
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 55 55 target 0
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 55 55 target 4
	walkframe 55 LX LY
}

$Animation "a_CrouchWalk_RifleNE" "survivor_biker_anims\a_CrouchWalk_RifleNE.smd" {
	fps 27.4
	loop
	ikrule "lhand" touch "ValveBiped.Bip01_R_Hand" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 55 55 target 1
	ikrule "lfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 55 55 target 3
	ikrule "rfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 55 55 target 2
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 55 55 target 0
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 55 55 target 4
	walkframe 55 LX LY
}

$Animation "a_CrouchWalk_RifleNW" "survivor_biker_anims\a_CrouchWalk_RifleNW.smd" {
	fps 27.4
	loop
	ikrule "lhand" touch "ValveBiped.Bip01_R_Hand" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 55 55 target 1
	ikrule "lfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 55 55 target 3
	ikrule "rfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 55 55 target 2
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 55 55 target 0
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 55 55 target 4
	walkframe 55 LX LY
}

$Animation "a_CrouchWalk_RifleW" "survivor_biker_anims\a_CrouchWalk_RifleW.smd" {
	fps 27.4
	loop
	ikrule "lhand" touch "ValveBiped.Bip01_R_Hand" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 55 55 target 1
	ikrule "lfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 55 55 target 3
	ikrule "rfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 55 55 target 2
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 55 55 target 0
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 55 55 target 4
	walkframe 55 LX LY
}

$Animation "a_CrouchWalk_RifleSW" "survivor_biker_anims\a_CrouchWalk_RifleSW.smd" {
	fps 24.96
	loop
	ikrule "lhand" touch "ValveBiped.Bip01_R_Hand" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 49 49 target 1
	ikrule "lfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 49 49 target 3
	ikrule "rfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 49 49 target 2
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 49 49 target 0
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 49 49 target 4
	walkframe 49 LX LY
}

$Animation "a_CrouchWalk_RifleZero" "survivor_biker_anims\a_CrouchWalk_RifleZero.smd" {
	fps 30
	loop
	ikrule "lhand" touch "ValveBiped.Bip01_R_Hand" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 99 99 target 1
	ikrule "lfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 99 99 target 3
	ikrule "rfoot" touch "" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 99 99 target 2
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 99 99 target 0
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 99 99 target 4
}

$Animation "a_NamVet_AimMatrix_Rifle_Crouching_neutral" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Crouching_neutral.smd" {
	fps 30
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 1
	ikrule "rfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 2
	ikrule "lfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 3
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 4
}

$Animation "a_NamVet_AimMatrix_Rifle_Crouching_down_right" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Crouching_down_right.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_Crouching_down_right_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_Crouching_down_center" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Crouching_down_center.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_Crouching_down_center_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_Crouching_down_left" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Crouching_down_left.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_Crouching_down_left_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_Crouching_mid_right" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Crouching_mid_right.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_Crouching_mid_right_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_Crouching_mid_center" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Crouching_mid_center.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_Crouching_mid_center_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_Crouching_mid_left" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Crouching_mid_left.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_Crouching_mid_left_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_Crouching_up_right" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Crouching_up_right.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_Crouching_up_right_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_Crouching_up_center" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Crouching_up_center.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_Crouching_up_center_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_Crouching_up_left" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Crouching_up_left.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_Crouching_up_left_corrective_animation" 0
}

$Animation "a_NamVet_AimMatrix_Rifle_Crouching_straight_up" "survivor_biker_anims\a_NamVet_AimMatrix_Rifle_Crouching_straight_up.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_NamVet_AimMatrix_Rifle_Crouching_straight_up_corrective_animation" 0
}

$Sequence "Biker" {
	"survivor_biker_anims\Biker.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 1
	ikrule "rfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 2
	ikrule "lfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 3
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 4
}

$Sequence "animHack" {
	"survivor_biker_anims\animHack.smd"
	fadein 0.2
	fadeout 0.2
	hidden
	fps 30
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 10 10 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 10 10 target 1
	ikrule "rfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 10 10 target 2
	ikrule "lfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 10 10 target 3
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 10 10 target 4
}

$Sequence "Heal_Self_Standing_06" {
	"survivor_biker_anims\Heal_Self_Standing_06.smd"
	activity "ACT_TERROR_HEAL_SELF" 1
	{ event AE_CL_CREATE_PARTICLE_EFFECT 35 "bandage_01 follow_attachment armL_B follow_attachment armL" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 99 "bandage_01 follow_attachment legL_B follow_attachment legL" }
	fadein 0.75
	fadeout 0.75
	fps 33.6
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 168 168 target 1
}

$Sequence "Idlenoise" {
	"survivor_biker_anims\Idlenoise.smd"
	delta
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "@Idlenoise_corrective_animation" 0
	fadein 0.2
	fadeout 0.2
	hidden
	iklock "lfoot" 1 0
	iklock "rfoot" 1 0
	fps 30
	loop
	weightlist "weights_Idlenoise"
}

$Sequence "Idle_Standing_Align" {
	"survivor_biker_anims\Idle_Standing_Align.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 1
	ikrule "rfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 2
	ikrule "lfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 3
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 4
}

$Sequence "Idle_Standing_Rifle" {
	"a_francis_AimMatrix_Rifle_Standing"
	activity "ACT_IDLE_RIFLE" -1
	fadein 0.5
	fadeout 0.5
	addlayer "NamVet_AimMatrix_Rifle_Standing"
	addlayer "Idlenoise"
}

$Sequence "NamVet_AimMatrix_Rifle_Walking" {
	"a_NamVet_AimMatrix_Rifle_Walking_straight_up"
	"a_NamVet_AimMatrix_Rifle_Walking_straight_up"
	"a_NamVet_AimMatrix_Rifle_Walking_straight_up"
	"a_NamVet_AimMatrix_Rifle_Walking_up_right"
	"a_NamVet_AimMatrix_Rifle_Walking_up_center"
	"a_NamVet_AimMatrix_Rifle_Walking_up_left"
	"a_NamVet_AimMatrix_Rifle_Walking_mid_right"
	"a_NamVet_AimMatrix_Rifle_Walking_mid_center"
	"a_NamVet_AimMatrix_Rifle_Walking_mid_left"
	"a_NamVet_AimMatrix_Rifle_Walking_down_right"
	"a_NamVet_AimMatrix_Rifle_Walking_down_center"
	"a_NamVet_AimMatrix_Rifle_Walking_down_left"
	blend "body_yaw" -90 90
	blend "body_pitch" -90 45
	blendwidth 3
	delta
	fadein 0.2
	fadeout 0.2
	hidden
	iklock "rfoot" 1 0
	iklock "lfoot" 1 0
}

$Sequence "NamVet_AimMatrix_Rifle_CrouchWalking" {
	"a_NamVet_AimMatrix_Rifle_CrouchWalking_straight_up"
	"a_NamVet_AimMatrix_Rifle_CrouchWalking_straight_up"
	"a_NamVet_AimMatrix_Rifle_CrouchWalking_straight_up"
	"a_NamVet_AimMatrix_Rifle_CrouchWalking_up_right"
	"a_NamVet_AimMatrix_Rifle_CrouchWalking_up_center"
	"a_NamVet_AimMatrix_Rifle_CrouchWalking_up_left"
	"a_NamVet_AimMatrix_Rifle_CrouchWalking_mid_right"
	"a_NamVet_AimMatrix_Rifle_CrouchWalking_mid_center"
	"a_NamVet_AimMatrix_Rifle_CrouchWalking_mid_left"
	"a_NamVet_AimMatrix_Rifle_CrouchWalking_down_right"
	"a_NamVet_AimMatrix_Rifle_CrouchWalking_down_center"
	"a_NamVet_AimMatrix_Rifle_CrouchWalking_down_left"
	blend "body_yaw" -90 90
	blend "body_pitch" -90 45
	blendwidth 3
	delta
	fadein 0.2
	fadeout 0.2
	hidden
	iklock "rfoot" 1 0
	iklock "lfoot" 1 0
}

$Sequence "NamVet_AimMatrix_Rifle_Standing_Calm" {
	"a_NamVet_AimMatrix_Rifle_Standing_Calm_straight_up"
	"a_NamVet_AimMatrix_Rifle_Standing_Calm_straight_up"
	"a_NamVet_AimMatrix_Rifle_Standing_Calm_straight_up"
	"a_NamVet_AimMatrix_Rifle_Standing_Calm_up_right"
	"a_NamVet_AimMatrix_Rifle_Standing_Calm_up_center"
	"a_NamVet_AimMatrix_Rifle_Standing_Calm_up_left"
	"a_NamVet_AimMatrix_Rifle_Standing_Calm_mid_right"
	"a_NamVet_AimMatrix_Rifle_Standing_Calm_mid_center"
	"a_NamVet_AimMatrix_Rifle_Standing_Calm_mid_left"
	"a_NamVet_AimMatrix_Rifle_Standing_Calm_down_right"
	"a_NamVet_AimMatrix_Rifle_Standing_Calm_down_center"
	"a_NamVet_AimMatrix_Rifle_Standing_Calm_down_left"
	blend "body_yaw" -90 90
	blend "body_pitch" -90 45
	blendwidth 3
	delta
	fadein 0.2
	fadeout 0.2
	hidden
	iklock "rfoot" 1 0
	iklock "lfoot" 1 0
}

$Sequence "NamVet_AimMatrix_Rifle_Standing" {
	"a_NamVet_AimMatrix_Rifle_Standing_straight_up"
	"a_NamVet_AimMatrix_Rifle_Standing_straight_up"
	"a_NamVet_AimMatrix_Rifle_Standing_straight_up"
	"a_NamVet_AimMatrix_Rifle_Standing_up_right"
	"a_NamVet_AimMatrix_Rifle_Standing_up_center"
	"a_NamVet_AimMatrix_Rifle_Standing_up_left"
	"a_NamVet_AimMatrix_Rifle_Standing_mid_right"
	"a_NamVet_AimMatrix_Rifle_Standing_mid_center"
	"a_NamVet_AimMatrix_Rifle_Standing_mid_left"
	"a_NamVet_AimMatrix_Rifle_Standing_down_right"
	"a_NamVet_AimMatrix_Rifle_Standing_down_center"
	"a_NamVet_AimMatrix_Rifle_Standing_down_left"
	blend "body_yaw" -90 90
	blend "body_pitch" -90 45
	blendwidth 3
	delta
	fadein 0.2
	fadeout 0.2
	hidden
	iklock "rfoot" 1 0
	iklock "lfoot" 1 0
}

$Sequence "francis_AimMatrix_Rifle_Running" {
	"a_francis_AimMatrix_Rifle_Running_straight_up"
	"a_francis_AimMatrix_Rifle_Running_straight_up"
	"a_francis_AimMatrix_Rifle_Running_straight_up"
	"a_francis_AimMatrix_Rifle_Running_up_right"
	"a_francis_AimMatrix_Rifle_Running_up_center"
	"a_francis_AimMatrix_Rifle_Running_up_left"
	"a_francis_AimMatrix_Rifle_Running_mid_right"
	"a_francis_AimMatrix_Rifle_Running_mid_center"
	"a_francis_AimMatrix_Rifle_Running_mid_left"
	"a_francis_AimMatrix_Rifle_Running_down_right"
	"a_francis_AimMatrix_Rifle_Running_down_center"
	"a_francis_AimMatrix_Rifle_Running_down_left"
	blend "body_yaw" -90 90
	blend "body_pitch" -90 45
	blendwidth 3
	delta
	fadein 0.2
	fadeout 0.2
	hidden
	iklock "rfoot" 1 0
	iklock "lfoot" 1 0
}

$Sequence "Run_Rifle" {
	"a_Run_RifleNW"
	"a_Run_RifleN"
	"a_Run_RifleNE"
	"a_Run_RifleW"
	"a_Run_RifleZero"
	"a_Run_RifleE"
	"a_Run_RifleSW"
	"a_Run_RifleS"
	"a_Run_RifleSE"
	activity "ACT_RUN_RIFLE" -1
	blend "move_y" -1 1
	blend "move_x" 1 -1
	{ event AE_FOOTSTEP_RIGHT 7 "" }
	{ event AE_FOOTSTEP_LEFT 18 "" }
	{ event AE_FOOTSTEP_RIGHT 27 "" }
	{ event AE_FOOTSTEP_LEFT 37 "" }
	fadein 0.5
	fadeout 0.5
	addlayer "francis_AimMatrix_Rifle_Running"
}

$Sequence "idle_axe_mdl" {
	"survivor_biker_anims\idle_axe_mdl.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 85 85 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 85 85 target 1
	ikrule "rfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 85 85 target 2
	ikrule "lfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 85 85 target 3
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 85 85 target 4
}

$Sequence "ragdoll" {
	"survivor_biker_anims\ragdoll.smd"
	activity "ACT_DIERAGDOLL" 1
	fadein 0.2
	fadeout 0.2
	fps 30
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 1 1 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 1 1 target 1
	ikrule "rfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 1 1 target 2
	ikrule "lfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 1 1 target 3
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 1 1 target 4
}

$DeclareSequence "InjuredIdlenoise"

$DeclareSequence "CalmIdlenoise"

$DeclareSequence "CalmIdlenoisePistol"

$DeclareSequence "NamVet_AimMatrix_Pistol_Standing_layer"

$DeclareSequence "NamVet_AimMatrix_Pistol_Standing_arms"

$DeclareSequence "Idle_Standing_Pistol"

$DeclareSequence "NamVet_AimMatrix_Elites_Standing_layer"

$DeclareSequence "NamVet_AimMatrix_Elites_Standing_arms"

$DeclareSequence "Idle_Standing_Elites"

$DeclareSequence "NamVet_Reload_Rifle_Standing_layer"

$DeclareSequence "NamVet_Reload_Rifle_Standing_arms"

$DeclareSequence "NamVet_AimMatrix_Shotgun_Standing_layer"

$DeclareSequence "NamVet_AimMatrix_Shotgun_Standing_arms"

$DeclareSequence "Idle_Standing_Shotgun"

$DeclareSequence "NamVet_AimMatrix_PumpShotgun_Standing_layer"

$DeclareSequence "NamVet_AimMatrix_PumpShotgun_Standing_arms"

$DeclareSequence "Idle_Standing_PumpShotgun"

$DeclareSequence "NamVet_AimMatrix_Grenade_Standing_layer"

$DeclareSequence "NamVet_AimMatrix_Grenade_Standing_arms"

$DeclareSequence "Idle_Standing_Grenade"

$DeclareSequence "NamVet_Idle_FirstAidKit_layer"

$DeclareSequence "NamVet_Idle_FirstAidKit_arms"

$DeclareSequence "Idle_Standing_FirstAidKit"

$DeclareSequence "NamVet_AimMatrix_SMG_Standing_layer"

$DeclareSequence "NamVet_AimMatrix_SMG_Standing_arms"

$DeclareSequence "Idle_Standing_SMG"

$DeclareSequence "NamVet_AimMatrix_Sniper_Standing_layer"

$DeclareSequence "NamVet_AimMatrix_Sniper_Standing_arms"

$DeclareSequence "Idle_Standing_Sniper"

$DeclareSequence "NamVet_AimMatrix_SniperZoomed_Standing_layer"

$DeclareSequence "NamVet_AimMatrix_SniperZoomed_Standing_arms"

$DeclareSequence "Idle_Standing_SniperZoomed"

$DeclareSequence "NamVet_AimMatrix_gasCan_Standing_layer"

$DeclareSequence "NamVet_AimMatrix_gasCan_Standing_arms"

$DeclareSequence "Idle_Standing_GasCan"

$DeclareSequence "NamVet_AimMatrix_o2_Standing_layer"

$DeclareSequence "NamVet_AimMatrix_o2_Standing_arms"

$DeclareSequence "Idle_Standing_o2"

$DeclareSequence "Idle_Crouching_Pistol"

$DeclareSequence "Idle_Crouching_Elites"

$Sequence "Idle_Crouching_Rifle" {
	"a_francis_AimMatrix_Rifle_Crouching"
	activity "ACT_CROUCHIDLE_RIFLE" -1
	fadein 0.5
	fadeout 0.5
	addlayer "NamVet_AimMatrix_Rifle_Crouching"
	addlayer "Idlenoise"
}

$DeclareSequence "Idle_Crouching_Shotgun"

$DeclareSequence "Idle_Crouching_PumpShotgun"

$DeclareSequence "Idle_Crouching_Grenade"

$DeclareSequence "Idle_Crouching_FirstAidKit"

$DeclareSequence "Idle_Crouching_SMG"

$DeclareSequence "Idle_Crouching_Sniper"

$DeclareSequence "Idle_Crouching_SniperZoomed"

$DeclareSequence "Idle_Crouching_GasCan"

$DeclareSequence "Idle_Crouching_o2"

$DeclareSequence "NamVet_AimMatrix_Pistol_Standing_Calm_layer"

$DeclareSequence "NamVet_AimMatrix_Pistol_Standing_Calm_arms"

$DeclareSequence "Idle_Calm_Pistol"

$DeclareSequence "NamVet_AimMatrix_Elites_Standing_Calm_layer"

$DeclareSequence "NamVet_AimMatrix_Elites_Standing_Calm_arms"

$DeclareSequence "Idle_Calm_Elites"

$DeclareSequence "NamVet_AimMatrix_SMG_Standing_Calm_layer"

$DeclareSequence "NamVet_AimMatrix_SMG_Standing_Calm_arms"

$DeclareSequence "Idle_Calm_SMG"

$DeclareSequence "NamVet_AimMatrix_Rifle_Standing_Calm_layer"

$DeclareSequence "NamVet_AimMatrix_Rifle_Standing_Calm_arms"

$DeclareSequence "Idle_Calm_Rifle"

$DeclareSequence "NamVet_AimMatrix_Shotgun_Standing_Calm_layer"

$DeclareSequence "NamVet_AimMatrix_Shotgun_Standing_Calm_arms"

$DeclareSequence "Idle_Calm_Shotgun"

$DeclareSequence "NamVet_AimMatrix_Sniper_Standing_Calm_layer"

$DeclareSequence "NamVet_AimMatrix_Sniper_Standing_Calm_arms"

$DeclareSequence "Idle_Calm_Sniper"

$DeclareSequence "NamVet_AimMatrix_PumpShotgun_Standing_Calm_layer"

$DeclareSequence "NamVet_AimMatrix_PumpShotgun_Standing_Calm_arms"

$DeclareSequence "Idle_Calm_PumpShotgun"

$DeclareSequence "NamVet_AimMatrix_gasCan_Standing_Calm_layer"

$DeclareSequence "NamVet_AimMatrix_gasCan_Standing_Calm_arms"

$DeclareSequence "Idle_Calm_GasCan"

$DeclareSequence "NamVet_AimMatrix_O2_Standing_Calm_layer"

$DeclareSequence "NamVet_AimMatrix_O2_Standing_Calm_arms"

$DeclareSequence "Idle_Calm_O2"

$DeclareSequence "NamVet_AimMatrix_Pistol_Injured_Standing_layer"

$DeclareSequence "NamVet_AimMatrix_Pistol_Injured_Standing_arms"

$DeclareSequence "Idle_Injured_Pistol"

$DeclareSequence "NamVet_AimMatrix_Elites_Injured_Standing_layer"

$DeclareSequence "NamVet_AimMatrix_Elites_Injured_Standing_arms"

$DeclareSequence "Idle_Injured_Elites"

$DeclareSequence "NamVet_AimMatrix_Rifle_Injured_Standing_layer"

$DeclareSequence "NamVet_AimMatrix_Rifle_Injured_Standing_arms"

$DeclareSequence "Idle_Injured_Rifle"

$DeclareSequence "NamVet_AimMatrix_Grenade_Injured_Standing_layer"

$DeclareSequence "NamVet_AimMatrix_Grenade_Injured_Standing_arms"

$DeclareSequence "Idle_Injured_Grenade"

$DeclareSequence "NamVet_AimMatrix_FirstAidKit_Injured_Standing_layer"

$DeclareSequence "NamVet_AimMatrix_FirstAidKit_Injured_Standing_arms"

$DeclareSequence "Idle_Injured_FirstAidKit"

$DeclareSequence "NamVet_AimMatrix_SMG_Injured_Standing_layer"

$DeclareSequence "NamVet_AimMatrix_SMG_Injured_Standing_arms"

$DeclareSequence "Idle_Injured_SMG"

$DeclareSequence "NamVet_AimMatrix_PumpShotgun_Injured_Standing_layer"

$DeclareSequence "NamVet_AimMatrix_PumpShotgun_Injured_Standing_arms"

$DeclareSequence "Idle_Injured_PumpShotgun"

$DeclareSequence "NamVet_AimMatrix_Sniper_Injured_Standing_layer"

$DeclareSequence "NamVet_AimMatrix_Sniper_Injured_Standing_arms"

$DeclareSequence "Idle_Injured_Sniper"

$DeclareSequence "NamVet_AimMatrix_SniperZoomed_Injured_Standing_layer"

$DeclareSequence "NamVet_AimMatrix_SniperZoomed_Injured_Standing_arms"

$DeclareSequence "Idle_Injured_SniperZoomed"

$DeclareSequence "NamVet_AimMatrix_gasCan_Injured_Standing_layer"

$DeclareSequence "NamVet_AimMatrix_gasCan_Injured_Standing_arms"

$DeclareSequence "Idle_Injured_GasCan"

$DeclareSequence "NamVet_AimMatrix_o2_Injured_Standing_layer"

$DeclareSequence "NamVet_AimMatrix_o2_Injured_Standing_arms"

$DeclareSequence "Idle_Injured_O2"

$DeclareSequence "Turn"

$DeclareSequence "Turn_02"

$DeclareSequence "WalkN_Pistol_layer"

$DeclareSequence "WalkN_Pistol_arms"

$DeclareSequence "Walk_Pistol"

$DeclareSequence "WalkN_Elites_layer"

$DeclareSequence "WalkN_Elites_arms"

$DeclareSequence "Walk_Elites"

$DeclareSequence "WalkN_Shotgun_layer"

$DeclareSequence "WalkN_Shotgun_arms"

$DeclareSequence "Walk_Shotgun"

$DeclareSequence "WalkN_Grenade_layer"

$DeclareSequence "WalkN_Grenade_arms"

$DeclareSequence "Walk_Grenade"

$DeclareSequence "WalkN_FirstAidKit_layer"

$DeclareSequence "WalkN_FirstAidKit_arms"

$DeclareSequence "Walk_FirstAidKit"

$DeclareSequence "WalkN_SMG_layer"

$DeclareSequence "WalkN_SMG_arms"

$DeclareSequence "Walk_SMG"

$DeclareSequence "WalkN_Sniper_layer"

$DeclareSequence "WalkN_Sniper_arms"

$DeclareSequence "Walk_Sniper"

$DeclareSequence "WalkN_PumpShotgun_layer"

$DeclareSequence "WalkN_PumpShotgun_arms"

$DeclareSequence "Walk_PumpShotgun"

$DeclareSequence "WalkN_GasCan_layer"

$DeclareSequence "WalkN_GasCan_arms"

$DeclareSequence "Walk_GasCan"

$DeclareSequence "WalkN_O2_layer"

$DeclareSequence "WalkN_O2_arms"

$DeclareSequence "Walk_O2"

$DeclareSequence "CrouchWalkN_Pistol_layer"

$DeclareSequence "CrouchWalkN_Pistol_arms"

$DeclareSequence "CrouchWalk_Pistol"

$DeclareSequence "CrouchWalkN_Elites_layer"

$DeclareSequence "CrouchWalkN_Elites_arms"

$DeclareSequence "CrouchWalk_Elites"

$DeclareSequence "CrouchWalkN_Shotgun_layer"

$DeclareSequence "CrouchWalkN_Shotgun_arms"

$DeclareSequence "CrouchWalk_Shotgun"

$DeclareSequence "CrouchWalkN_Grenade_layer"

$DeclareSequence "CrouchWalkN_Grenade_arms"

$DeclareSequence "CrouchWalk_Grenade"

$DeclareSequence "CrouchWalkN_FirstAidKit_layer"

$DeclareSequence "CrouchWalkN_FirstAidKit_arms"

$DeclareSequence "CrouchWalk_FirstAidKit"

$DeclareSequence "CrouchWalkN_SMG_layer"

$DeclareSequence "CrouchWalkN_SMG_arms"

$DeclareSequence "CrouchWalk_SMG"

$DeclareSequence "CrouchWalkN_Sniper_layer"

$DeclareSequence "CrouchWalkN_Sniper_arms"

$DeclareSequence "CrouchWalk_Sniper"

$DeclareSequence "CrouchWalkN_PumpShotgun_layer"

$DeclareSequence "CrouchWalkN_PumpShotgun_arms"

$DeclareSequence "CrouchWalk_PumpShotgun"

$DeclareSequence "CrouchWalkN_GasCan_layer"

$DeclareSequence "CrouchWalkN_GasCan_arms"

$DeclareSequence "CrouchWalk_GasCan"

$DeclareSequence "CrouchWalkN_O2_layer"

$DeclareSequence "CrouchWalkN_O2_arms"

$DeclareSequence "CrouchWalk_O2"

$DeclareSequence "RunN_Pistol_layer"

$DeclareSequence "RunN_Pistol_arms"

$DeclareSequence "Run_Pistol"

$DeclareSequence "RunN_Elites_layer"

$DeclareSequence "RunN_Elites_arms"

$DeclareSequence "Run_Elites"

$DeclareSequence "RunN_Shotgun_layer"

$DeclareSequence "RunN_Shotgun_arms"

$DeclareSequence "Run_Shotgun"

$DeclareSequence "RunN_Grenade_layer"

$DeclareSequence "RunN_Grenade_arms"

$DeclareSequence "Run_Grenade"

$DeclareSequence "RunN_FirstAidKit_layer"

$DeclareSequence "RunN_FirstAidKit_arms"

$DeclareSequence "Run_FirstAidKit"

$DeclareSequence "RunN_SMG_layer"

$DeclareSequence "RunN_SMG_arms"

$DeclareSequence "Run_SMG"

$DeclareSequence "RunN_Sniper_layer"

$DeclareSequence "RunN_Sniper_arms"

$DeclareSequence "Run_Sniper"

$DeclareSequence "RunN_PumpShotgun_layer"

$DeclareSequence "RunN_PumpShotgun_arms"

$DeclareSequence "Run_PumpShotgun"

$DeclareSequence "RunN_GasCan_layer"

$DeclareSequence "RunN_GasCan_arms"

$DeclareSequence "Run_GasCan"

$DeclareSequence "RunN_O2_layer"

$DeclareSequence "RunN_O2_arms"

$DeclareSequence "Run_O2"

$DeclareSequence "CalmWalkN_Pistol_layer"

$DeclareSequence "CalmWalkN_Pistol_arms"

$DeclareSequence "CalmWalk_Pistol"

$DeclareSequence "CalmWalkN_Elites_layer"

$DeclareSequence "CalmWalkN_Elites_arms"

$DeclareSequence "CalmWalk_Elites"

$DeclareSequence "CalmWalkN_SMG_layer"

$DeclareSequence "CalmWalkN_SMG_arms"

$DeclareSequence "CalmWalk_SMG"

$DeclareSequence "CalmWalkN_Rifle_layer"

$DeclareSequence "CalmWalkN_Rifle_arms"

$DeclareSequence "CalmWalk_Rifle"

$DeclareSequence "CalmWalkN_Sniper_layer"

$DeclareSequence "CalmWalkN_Sniper_arms"

$DeclareSequence "CalmWalk_Sniper"

$DeclareSequence "CalmWalkN_PumpShotgun_layer"

$DeclareSequence "CalmWalkN_PumpShotgun_arms"

$DeclareSequence "CalmWalk_PumpShotgun"

$DeclareSequence "CalmRunN_Pistol_layer"

$DeclareSequence "CalmRunN_Pistol_arms"

$DeclareSequence "CalmRun_Pistol"

$DeclareSequence "CalmRunN_Elites_layer"

$DeclareSequence "CalmRunN_Elites_arms"

$DeclareSequence "CalmRun_Elites"

$DeclareSequence "CalmRunN_SMG_layer"

$DeclareSequence "CalmRunN_SMG_arms"

$DeclareSequence "CalmRun_SMG"

$DeclareSequence "CalmRunN_Rifle_layer"

$DeclareSequence "CalmRunN_Rifle_arms"

$DeclareSequence "CalmRun_Rifle"

$DeclareSequence "CalmRunN_Sniper_layer"

$DeclareSequence "CalmRunN_Sniper_arms"

$DeclareSequence "CalmRun_Sniper"

$DeclareSequence "CalmRunN_PumpShotgun_layer"

$DeclareSequence "CalmRunN_PumpShotgun_arms"

$DeclareSequence "CalmRun_PumpShotgun"

$Sequence "Walk_Rifle" {
	"a_Walk_RifleNW"
	"a_Walk_RifleN"
	"a_Walk_RifleNE"
	"a_Walk_RifleW"
	"a_Walk_RifleZero"
	"a_Walk_RifleE"
	"a_Walk_RifleSW"
	"a_Walk_RifleS"
	"a_Walk_RifleSE"
	activity "ACT_WALK_RIFLE" -1
	blend "move_y" -1 1
	blend "move_x" 1 -1
	{ event AE_FOOTSTEP_RIGHT 9 "" }
	{ event AE_FOOTSTEP_LEFT 23 "" }
	{ event AE_FOOTSTEP_RIGHT 38 "" }
	{ event AE_FOOTSTEP_LEFT 52 "" }
	fadein 0.5
	fadeout 0.5
	addlayer "NamVet_AimMatrix_Rifle_Walking"
}

$Sequence "CrouchWalk_Rifle" {
	"a_CrouchWalk_RifleNW"
	"a_CrouchWalk_RifleN"
	"a_CrouchWalk_RifleNE"
	"a_CrouchWalk_RifleW"
	"a_CrouchWalk_RifleZero"
	"a_CrouchWalk_RifleE"
	"a_CrouchWalk_RifleSW"
	"a_CrouchWalk_RifleS"
	"a_CrouchWalk_RifleSE"
	activity "ACT_RUN_CROUCH_RIFLE" -1
	blend "move_y" -1 1
	blend "move_x" 1 -1
	{ event AE_FOOTSTEP_RIGHT 8 "" }
	{ event AE_FOOTSTEP_LEFT 22 "" }
	{ event AE_FOOTSTEP_RIGHT 35 "" }
	{ event AE_FOOTSTEP_LEFT 49 "" }
	fadein 0.75
	fadeout 0.5
	addlayer "NamVet_AimMatrix_Rifle_CrouchWalking"
}

$DeclareSequence "LimpWalk_Pistol"

$DeclareSequence "LimpWalk_Elites"

$DeclareSequence "LimpWalk_Rifle"

$DeclareSequence "LimpWalk_Grenade"

$DeclareSequence "LimpWalk_FirstAidKit"

$DeclareSequence "LimpWalk_SMG"

$DeclareSequence "LimpWalk_Sniper"

$DeclareSequence "LimpWalk_PumpShotgun"

$DeclareSequence "LimpWalk_GasCan"

$DeclareSequence "LimpWalk_O2"

$DeclareSequence "LimpRun_Pistol"

$DeclareSequence "LimpRun_Elites"

$DeclareSequence "LimpRun_Rifle"

$DeclareSequence "LimpRun_Grenade"

$DeclareSequence "LimpRun_FirstAidKit"

$DeclareSequence "LimpRun_SMG"

$DeclareSequence "LimpRun_Sniper"

$DeclareSequence "LimpRun_PumpShotgun"

$DeclareSequence "LimpRun_GasCan"

$DeclareSequence "LimpRun_O2"

$DeclareSequence "Push_Pull"

$DeclareSequence "NamVet_AimMatrix_Pistol_Standing"

$DeclareSequence "NamVet_AimMatrix_Pistol_CrouchWalking"

$DeclareSequence "NamVet_AimMatrix_Pistol_Injured_Standing"

$DeclareSequence "NamVet_AimMatrix_Pistol_LimpRunning"

$DeclareSequence "NamVet_AimMatrix_Pistol_Standing_Calm"

$DeclareSequence "NamVet_AimMatrix_Pistol_Standing_Calm_Checkpoint"

$DeclareSequence "NamVet_AimMatrix_Elites_Standing"

$DeclareSequence "NamVet_AimMatrix_Elites_Injured_Standing"

$DeclareSequence "NamVet_AimMatrix_Elites_Walking"

$DeclareSequence "NamVet_AimMatrix_Elites_Running"

$DeclareSequence "NamVet_AimMatrix_Elites_CrouchWalking"

$DeclareSequence "NamVet_AimMatrix_Elites_LimpWalking"

$DeclareSequence "NamVet_AimMatrix_Elites_LimpRunning"

$DeclareSequence "NamVet_AimMatrix_Rifle_Running"

$DeclareSequence "NamVet_AimMatrix_Rifle_LimpRunning"

$DeclareSequence "NamVet_AimMatrix_Shotgun_Standing"

$DeclareSequence "NamVet_AimMatrix_Shotgun_CrouchWalking"

$DeclareSequence "NamVet_AimMatrix_Grenade_Standing"

$DeclareSequence "NamVet_AimMatrix_Grenade_Crouching"

$DeclareSequence "NamVet_AimMatrix_Grenade_CrouchWalking"

$DeclareSequence "NamVet_AimMatrix_Shoot_Grenade_Standing_Ready"

$DeclareSequence "NamVet_AimMatrix_Shoot_Grenade_Standing"

$DeclareSequence "NamVet_AimMatrix_Shoot_Grenade_Running"

$DeclareSequence "NamVet_AimMatrix_SMG_Standing_Calm"

$DeclareSequence "NamVet_AimMatrix_SMG_Standing"

$DeclareSequence "NamVet_AimMatrix_SMG_Crouching"

$DeclareSequence "NamVet_AimMatrix_SMG_Walking"

$DeclareSequence "NamVet_AimMatrix_SMG_CrouchWalking"

$DeclareSequence "NamVet_AimMatrix_Sniper_Standing"

$DeclareSequence "NamVet_AimMatrix_SniperZoomed_Injured_Standing"

$DeclareSequence "NamVet_AimMatrix_SniperZoomed_Standing"

$DeclareSequence "NamVet_AimMatrix_Sniper_Crouching"

$DeclareSequence "NamVet_AimMatrix_SniperZoomed_Crouching"

$DeclareSequence "NamVet_AimMatrix_PumpShotgun_Standing"

$DeclareSequence "NamVet_AimMatrix_PumpShotgun_Walking"

$DeclareSequence "NamVet_AimMatrix_PumpShotgun_Running"

$DeclareSequence "NamVet_AimMatrix_PumpShotgun_CrouchWalking"

$DeclareSequence "NamVet_AimMatrix_PumpShotgun_LimpRunning"

$DeclareSequence "NamVet_AimMatrix_Pickup_Rifle_Standing"

$DeclareSequence "NamVet_AimMatrix_Melee_Sweep_Rifle_Standing"

$DeclareSequence "NamVet_AimMatrix_Melee_Shove_Rifle_Standing"

$DeclareSequence "NamVet_AimMatrix_Melee_Straight_Rifle_Standing"

$DeclareSequence "NamVet_AimMatrix_Melee_Sweep_Rifle_Running"

$DeclareSequence "NamVet_AimMatrix_Melee_Sweep_Rifle_Running_03"

$DeclareSequence "NamVet_AimMatrix_gasCan_Standing"

$DeclareSequence "NamVet_AimMatrix_gasCan_Crouching"

$DeclareSequence "NamVet_AimMatrix_gasCan_Injured_Standing"

$DeclareSequence "NamVet_AimMatrix_o2_Standing"

$DeclareSequence "NamVet_AimMatrix_o2_Crouching"

$DeclareSequence "NamVet_AimMatrix_o2_Injured_Standing"

$DeclareSequence "NamVet_AimMatrix_Pistol_Crouching"

$Sequence "NamVet_AimMatrix_Rifle_Crouching" {
	"a_NamVet_AimMatrix_Rifle_Crouching_straight_up"
	"a_NamVet_AimMatrix_Rifle_Crouching_straight_up"
	"a_NamVet_AimMatrix_Rifle_Crouching_straight_up"
	"a_NamVet_AimMatrix_Rifle_Crouching_up_right"
	"a_NamVet_AimMatrix_Rifle_Crouching_up_center"
	"a_NamVet_AimMatrix_Rifle_Crouching_up_left"
	"a_NamVet_AimMatrix_Rifle_Crouching_mid_right"
	"a_NamVet_AimMatrix_Rifle_Crouching_mid_center"
	"a_NamVet_AimMatrix_Rifle_Crouching_mid_left"
	"a_NamVet_AimMatrix_Rifle_Crouching_down_right"
	"a_NamVet_AimMatrix_Rifle_Crouching_down_center"
	"a_NamVet_AimMatrix_Rifle_Crouching_down_left"
	blend "body_yaw" -90 90
	blend "body_pitch" -90 45
	blendwidth 3
	delta
	fadein 0.2
	fadeout 0.2
	hidden
}

$DeclareSequence "NamVet_AimMatrix_Elites_Crouching"

$DeclareSequence "NamVet_AimMatrix_Shotgun_Crouching"

$DeclareSequence "NamVet_AimMatrix_PumpShotgun_Crouching"

$DeclareSequence "NamVet_AimMatrix_Pistol_Incap"

$DeclareSequence "NamVet_AimMatrix_Elites_Incap"

$DeclareSequence "NamVet_AimMatrix_Ladder_Climb"

$DeclareSequence "DummyAim"

$DeclareSequence "NamVet_BodyLeans"

$DeclareSequence "NamVet_AimMatrix_MiniGun"

$DeclareSequence "Idle_Standing_Minigun"

$DeclareSequence "Shoot_Standing_Minigun"

$DeclareSequence "Shoot_Standing_PISTOL"

$DeclareSequence "Shoot_Standing_ELITES_R"

$DeclareSequence "Shoot_Standing_ELITES_L"

$DeclareSequence "Shoot_Standing_RIFLE"

$DeclareSequence "Shoot_Standing_XM1014"

$DeclareSequence "Shoot_Standing_SMG"

$DeclareSequence "Shoot_Standing_M3S90"

$DeclareSequence "Shoot_Standing_PumpShotgun"

$DeclareSequence "Gren_Running_Subtract"

$DeclareSequence "Gren_Prep_Delta"

$DeclareSequence "Gren_Throw_Delta"

$DeclareSequence "Gren_Pull_Back_Delta"

$DeclareSequence "Gren_Pull_Back_layer"

$DeclareSequence "Shoot_Standing_Grenade1"

$DeclareSequence "Shoot_Standing_Grenade2"

$DeclareSequence "Shoot_Running_Grenade1"

$DeclareSequence "Shoot_Running_Grenade2"

$DeclareSequence "gasCan_Running_Subtract"

$DeclareSequence "gasCan_Prep_Delta"

$DeclareSequence "gasCan_Throw_Delta"

$DeclareSequence "gascan_pull_back_delta"

$DeclareSequence "gasCan_pull_back_layer"

$DeclareSequence "shoot_standing_gascan1"

$DeclareSequence "shoot_standing_gascan2"

$DeclareSequence "shoot_running_gascan1"

$DeclareSequence "shoot_running_gascan2"

$DeclareSequence "idle_gasCan_ready"

$DeclareSequence "o2_Running_Subtract"

$DeclareSequence "o2_Prep_Delta"

$DeclareSequence "o2_Throw_Delta"

$DeclareSequence "o2_pull_back_delta"

$DeclareSequence "o2_pull_back_layer"

$DeclareSequence "shoot_standing_o21"

$DeclareSequence "shoot_standing_o22"

$DeclareSequence "shoot_running_o21"

$DeclareSequence "shoot_running_o22"

$DeclareSequence "idle_o2_ready"

$DeclareSequence "NamVet_Shoot_Grenade_Standing_layer"

$DeclareSequence "NamVet_Shoot_Grenade_Standing_arms"

$DeclareSequence "Idle_Standing_Grenade_Ready"

$DeclareSequence "Idle_Crouching_Grenade_Ready"

$DeclareSequence "Idle_Injured_Grenade_Ready"

$DeclareSequence "Walk_Grenade_Ready"

$DeclareSequence "CrouchWalk_Grenade_Ready"

$DeclareSequence "Run_Grenade_Ready"

$DeclareSequence "LimpWalk_Grenade_Ready"

$DeclareSequence "LimpRun_Grenade_Ready"

$DeclareSequence "Walk_GasCan_Ready"

$DeclareSequence "CrouchWalk_GasCan_Ready"

$DeclareSequence "run_GasCan_Ready"

$DeclareSequence "Walk_O2_Ready"

$DeclareSequence "CrouchWalk_O2_Ready"

$DeclareSequence "run_O2_Ready"

$DeclareSequence "Melee_Sweep_Standing_Rifle_layer"

$DeclareSequence "Melee_Sweep_Standing_Rifle"

$DeclareSequence "Melee_Sweep_Running_Rifle_subtract"

$DeclareSequence "Melee_Sweep_Running_Rifle_Delta"

$DeclareSequence "Melee_Sweep_Running_Rifle_layer"

$DeclareSequence "Melee_Sweep_Running_Rifle"

$DeclareSequence "Melee_Shove_Standing_Rifle_layer"

$DeclareSequence "Melee_Shove_Standing_Rifle"

$DeclareSequence "Melee_Shove_Running_Rifle_subtract"

$DeclareSequence "Melee_Shove_Running_Rifle_Delta"

$DeclareSequence "Melee_Shove_Running_Rifle_layer"

$DeclareSequence "Melee_Shove_Running_Rifle"

$DeclareSequence "Melee_Straight_Standing_Rifle_layer"

$DeclareSequence "Melee_Straight_Standing_Rifle"

$DeclareSequence "Melee_Straight_Running_Rifle_subtract"

$DeclareSequence "Melee_Straight_Running_Rifle_Delta"

$DeclareSequence "Melee_Straight_Running_Rifle_layer"

$DeclareSequence "Melee_Straight_Running_Rifle"

$DeclareSequence "melee_sweep_gascan"

$DeclareSequence "melee_sweep_o2"

$DeclareSequence "Melee_Stomp_Standing_Rifle"

$DeclareSequence "Melee_Stomp_Walking_Rifle"

$DeclareSequence "Melee_Sweep_Standing_Rifle_02_layer"

$DeclareSequence "Melee_Sweep_Standing_Rifle_02"

$DeclareSequence "Melee_Sweep_Running_Rifle_02_subtract"

$DeclareSequence "Melee_Sweep_Running_Rifle_02_Delta"

$DeclareSequence "Melee_Sweep_Running_Rifle_02_layer"

$DeclareSequence "Melee_Sweep_Running_Rifle_02"

$DeclareSequence "Melee_Sweep_Standing_Rifle_03_layer"

$DeclareSequence "Melee_Sweep_Standing_Rifle_03"

$DeclareSequence "Melee_Sweep_Running_Rifle_03_subtract"

$DeclareSequence "Melee_Sweep_Running_Rifle_03_Delta"

$DeclareSequence "Melee_Sweep_Running_Rifle_03_layer"

$DeclareSequence "Melee_Sweep_Running_Rifle_03"

$DeclareSequence "Reload_Standing_Sniper_layer"

$DeclareSequence "Reload_Standing_Sniper"

$DeclareSequence "Reload_Standing_SMG_layer"

$DeclareSequence "Reload_Standing_SMG"

$DeclareSequence "Reload_Standing_Pistol_layer"

$DeclareSequence "Reload_Standing_Pistol"

$DeclareSequence "Reload_Standing_Rifle_layer"

$DeclareSequence "Reload_Standing_Rifle"

$DeclareSequence "Reload_Standing_Elites_layer"

$DeclareSequence "Reload_Standing_Elites"

$DeclareSequence "ShotgunReloadAim"

$DeclareSequence "PumpShotgunReloadAim"

$DeclareSequence "Reload_Standing_Shotgun_start"

$DeclareSequence "Reload_Standing_Shotgun_loop1"

$DeclareSequence "Reload_Standing_Shotgun_loop2"

$DeclareSequence "Reload_Standing_Shotgun_loop3"

$DeclareSequence "Reload_Standing_Shotgun_end"

$DeclareSequence "Reload_Standing_PumpShotgun_start"

$DeclareSequence "Reload_Standing_PumpShotgun_loop1"

$DeclareSequence "Reload_Standing_PumpShotgun_loop2"

$DeclareSequence "Reload_Standing_PumpShotgun_loop3"

$DeclareSequence "Reload_Standing_PumpShotgun_end"

$DeclareSequence "Fidget_Scratch_Face_Delta"

$DeclareSequence "Fidget_Scratch_Face_layer"

$DeclareSequence "Fidget_Scratch_Face"

$DeclareSequence "Fidget_Scratch_Nose_Delta"

$DeclareSequence "Fidget_Scratch_Nose_layer"

$DeclareSequence "Fidget_Scratch_Nose"

$DeclareSequence "Fidget_Scratch_Head_Delta"

$DeclareSequence "Fidget_Scratch_Head_layer"

$DeclareSequence "Fidget_Scratch_Head"

$DeclareSequence "Fidget_Wipe_Face_Delta"

$DeclareSequence "Fidget_Wipe_Face_layer"

$DeclareSequence "Fidget_Wipe_Face"

$DeclareSequence "Fidget_Wipe_Hand_Delta"

$DeclareSequence "Fidget_Wipe_Hand_layer"

$DeclareSequence "Fidget_Wipe_Hand"

$DeclareSequence "Fidget_Stretch_Neck"

$DeclareSequence "Fidget_Stretch_Back"

$DeclareSequence "Pickup_Standing_M4_subtract"

$DeclareSequence "Pickup_Standing_M4_delta"

$DeclareSequence "Pickup_Standing_M4_layer"

$DeclareSequence "Pickup_Standing_M4"

$DeclareSequence "Unholster_Standing_Pistol_layer"

$DeclareSequence "Unholster_Standing_Pistol"

$DeclareSequence "Unholster_Standing_Elites_layer"

$DeclareSequence "Unholster_Standing_Elites"

$DeclareSequence "Unholster_Standing_Rifle_layer"

$DeclareSequence "Unholster_Standing_Rifle"

$DeclareSequence "Unholster_Standing_Shotgun_layer"

$DeclareSequence "Unholster_Standing_Shotgun"

$DeclareSequence "Unholster_Standing_Gren_layer"

$DeclareSequence "Unholster_Standing_Gren"

$Sequence "Idle_Rescue_01c" {
	"survivor_biker_anims\Idle_Rescue_01c.smd"
	activity "ACT_CALL_FOR_RESCUE" -1
	fadein 0.2
	fadeout 0.2
	fps 36
	loop
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 244 244 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 244 244 target 1
	ikrule "rfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 244 244 target 2
	ikrule "lfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 244 244 target 3
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 244 244 target 4
}

$DeclareSequence "Heal_Self_Crouching"

$DeclareSequence "Heal_Self_Crouching_01"

$DeclareSequence "Heal_Incap_Standing"

$DeclareSequence "Heal_Incap_Standing_02"

$DeclareSequence "Heal_Incap_Standing_03"

$DeclareSequence "Heal_Incap_Crouching"

$DeclareSequence "Heal_Incap_Above_Standing"

$DeclareSequence "Heal_Incap_Above_Crouching"

$DeclareSequence "Heal_Friend_Standing"

$DeclareSequence "Heal_Friend_Crouching"

$DeclareSequence "Pills_Swallow_layer"

$DeclareSequence "Pills_Swallow"

$DeclareSequence "Jump_Rifle_01"

$DeclareSequence "Jump_Rifle_02"

$DeclareSequence "Jump_Shotgun_01"

$DeclareSequence "Jump_Shotgun_02"

$DeclareSequence "jump_gas_layer"

$DeclareSequence "jump_gas_gesture"

$DeclareSequence "jump_gas_gesture_aim"

$DeclareSequence "Jump_GasCan_01"

$DeclareSequence "Jump_GasCan_02"

$DeclareSequence "jump_o2_layer"

$DeclareSequence "jump_o2_gesture"

$DeclareSequence "jump_o2_gesture_aim"

$DeclareSequence "Jump_o2_01"

$DeclareSequence "Jump_o2_02"

$DeclareSequence "Jump_Smg_01"

$DeclareSequence "Jump_Smg_02"

$DeclareSequence "Jump_Pistol_01"

$DeclareSequence "Jump_Pistol_02"

$DeclareSequence "Jump_DualPistols_01"

$DeclareSequence "Jump_DualPistols_02"

$DeclareSequence "Jump_Item_01"

$DeclareSequence "Jump_Item_02"

$DeclareSequence "Jump_Land_gesture"

$DeclareSequence "Fall"

$DeclareSequence "Land_Injured"

$DeclareSequence "Ladder_Idlenoise"

$DeclareSequence "Ladder_Ascend"

$DeclareSequence "Ladder_Descend"

$DeclareSequence "Pulled_Running_Rifle"

$DeclareSequence "IncapIdlenoise"

$DeclareSequence "Death"

$DeclareSequence "Idle_Incap"

$DeclareSequence "Idle_Incap_Pistol"

$DeclareSequence "Idle_Incap_Elites"

$DeclareSequence "GetUpFrom_Incap"

$DeclareSequence "GetUpFrom_Incap_04"

$DeclareSequence "GetUpFrom_Incap_05"

$DeclareSequence "GetUpFrom_Incap_Crouching_01"

$DeclareSequence "Collapse_to_Incap_Pounced"

$DeclareSequence "Idle_Incap_Pounced"

$DeclareSequence "GetUpFrom_Pounced"

$DeclareSequence "Collapse_to_Incap_Tongue_germany"

$DeclareSequence "Idle_Incap_Hanging_SmokerChoke_germany"

$DeclareSequence "Idle_Fall_From_Tongue_germany"

$DeclareSequence "Idle_Incap_Standing_SmokerChoke_germany"

$DeclareSequence "Idle_Tongued_choking_ground"

$DeclareSequence "Idle_Tongued_Dragging_Ground"

$DeclareSequence "GetUpFrom_TankRock"

$DeclareSequence "Hit_by_TankPunch"

$DeclareSequence "Idle_Fall_From_TankPunch"

$DeclareSequence "GetUpFrom_TankPunch"

$DeclareSequence "incap_crawl"

$DeclareSequence "incap_drag_front"

$DeclareSequence "incap_drag_back"

$DeclareSequence "incap_drag_left"

$DeclareSequence "incap_drag_right"

$DeclareSequence "drag"

$DeclareSequence "Idle_Incap_Hanging1"

$DeclareSequence "Idle_Incap_Hanging2"

$DeclareSequence "Idle_Incap_Hanging3"

$DeclareSequence "Collapse_to_Hanging"

$DeclareSequence "GetUpFrom_Ledge"

$DeclareSequence "GetUpFrom_Ledge_Crouching"

$DeclareSequence "Idle_Falling"

$DeclareSequence "Death_10ab"

$DeclareSequence "deathpose_front"

$DeclareSequence "deathpose_back"

$DeclareSequence "deathpose_right"

$DeclareSequence "deathpose_left"

$DeclareSequence "Flinch_01"

$DeclareSequence "Flinch_02"

$DeclareSequence "Flinch_03"

$DeclareSequence "Flinch_Ledge_01"

$DeclareSequence "Flinch_Ledge_02"

$DeclareSequence "Flinch_Ledge_03"

$DeclareSequence "CalmIdlenoiseRealtime"

$DeclareSequence "Idle_Standing_fry_pan"

$DeclareSequence "coach_AimMatrix_Sniper_Military_Standing_layer"

$DeclareSequence "coach_AimMatrix_Sniper_Military_Standing_arms"

$DeclareSequence "Idle_Standing_Sniper_military"

$DeclareSequence "coach_AimMatrix_Sniper_militaryZoomed_Standing_layer"

$DeclareSequence "coach_AimMatrix_Sniper_militaryZoomed_Standing_arms"

$DeclareSequence "Idle_Standing_Sniper_militaryZoomed"

$DeclareSequence "Idle_Crouching_Frying_Pan"

$DeclareSequence "Idle_Crouching_Sniper_Military"

$DeclareSequence "Idle_Crouching_Sniper_MilitaryZoomed"

$DeclareSequence "Idle_Calm_Frying_Pan"

$DeclareSequence "Coach_AimMatrix_Sniper_Military_Standing_Calm_layer"

$DeclareSequence "Coach_AimMatrix_Sniper_Military_Standing_Calm_arms"

$DeclareSequence "Idle_Calm_Sniper_Military"

$DeclareSequence "Coach_AimMatrix_Sniper_Military_Injured_Standing_layer"

$DeclareSequence "Coach_AimMatrix_Sniper_Military_Injured_Standing_arms"

$DeclareSequence "Idle_Injured_Sniper_Military"

$DeclareSequence "Coach_AimMatrix_Sniper_MilitaryZoomed_Injured_Standing_layer"

$DeclareSequence "Coach_AimMatrix_Sniper_MilitaryZoomed_Injured_Standing_arms"

$DeclareSequence "Idle_Injured_Sniper_MilitaryZoomed"

$DeclareSequence "idle_standing_bat"

$DeclareSequence "Idle_Crouching_bat"

$DeclareSequence "Idle_Calm_bat"

$DeclareSequence "idle_injured_bat"

$DeclareSequence "CrouchWalkN_bat_layer"

$DeclareSequence "CrouchWalkN_bat_arms"

$DeclareSequence "CrouchWalk_bat"

$DeclareSequence "WalkN_bat_layer"

$DeclareSequence "WalkN_bat_arms"

$DeclareSequence "Walk_bat"

$DeclareSequence "RunN_bat_layer"

$DeclareSequence "RunN_bat_arms"

$DeclareSequence "Run_bat"

$DeclareSequence "LimpWalk_Bat"

$DeclareSequence "LimpRun_Bat"

$DeclareSequence "biker_AimMatrix_bat_Standing"

$DeclareSequence "biker_AimMatrix_bat_Crouching"

$DeclareSequence "biker_AimMatrix_bat_Injured_Standing"

$DeclareSequence "jump_bat_layer"

$DeclareSequence "Jump_bat_01"

$DeclareSequence "idle_axe_anim_mdl"

$DeclareSequence "Idle_Standing_axe"

$DeclareSequence "Idle_Crouching_axe"

$DeclareSequence "Idle_Calm_Axe"

$DeclareSequence "idle_injured_axe"

$DeclareSequence "CrouchWalkN_axe_layer"

$DeclareSequence "CrouchWalkN_axe_arms"

$DeclareSequence "CrouchWalk_axe"

$DeclareSequence "WalkN_axe_layer"

$DeclareSequence "WalkN_axe_arms"

$DeclareSequence "Walk_axe"

$DeclareSequence "RunN_Axe_layer"

$DeclareSequence "RunN_Axe_arms"

$DeclareSequence "Run_Axe"

$DeclareSequence "LimpWalk_Axe"

$DeclareSequence "LimpRun_Axe"

$DeclareSequence "biker_AimMatrix_axe_Standing"

$DeclareSequence "biker_AimMatrix_axe_Crouching"

$DeclareSequence "biker_AimMatrix_axe_Injured_Standing"

$DeclareSequence "jump_axe_layer"

$DeclareSequence "Jump_axe_01"

$DeclareSequence "Idle_Injured_Frying_Pan"

$DeclareSequence "CrouchWalkN_Frying_Pan_layer"

$DeclareSequence "CrouchWalkN_Frying_Pan_arms"

$DeclareSequence "CrouchWalk_Frying_Pan"

$DeclareSequence "CrouchWalkN_Sniper_Military_layer"

$DeclareSequence "CrouchWalkN_Sniper_Military_arms"

$DeclareSequence "CrouchWalk_Sniper_Military"

$DeclareSequence "WalkN_Sniper_Military_layer"

$DeclareSequence "WalkN_Sniper_Military_arms"

$DeclareSequence "Walk_Sniper_Military"

$DeclareSequence "WalkN_Frying_Pan_layer"

$DeclareSequence "WalkN_Frying_Pan_arms"

$DeclareSequence "Walk_Frying_Pan"

$DeclareSequence "RunN_Sniper_Military_layer"

$DeclareSequence "RunN_Sniper_Military_arms"

$DeclareSequence "Run_Sniper_Military"

$DeclareSequence "RunN_Frying_Pan_layer"

$DeclareSequence "RunN_Frying_Pan_arms"

$DeclareSequence "Run_Frying_Pan"

$DeclareSequence "CalmWalkN_Sniper_Military_layer"

$DeclareSequence "CalmWalkN_Sniper_Military_arms"

$DeclareSequence "CalmWalk_Sniper_Military"

$DeclareSequence "CalmRunN_Sniper_Military_layer"

$DeclareSequence "CalmRunN_Sniper_Military_arms"

$DeclareSequence "CalmRun_Sniper_Military"

$DeclareSequence "LimpWalk_Sniper_Military"

$DeclareSequence "LimpRun_Sniper_military"

$DeclareSequence "LimpWalk_Frying_Pan"

$DeclareSequence "LimpRun_Frying_Pan"

$DeclareSequence "coach_AimMatrix_Frying_Pan_Standing"

$DeclareSequence "coach_AimMatrix_Frying_Pan_Crouching"

$DeclareSequence "coach_AimMatrix_Frying_Pan_Injured_Standing"

$DeclareSequence "coach_AimMatrix_Sniper_Military_Standing"

$DeclareSequence "coach_AimMatrix_Sniper_MilitaryZoomed_Standing"

$DeclareSequence "coach_AimMatrix_Sniper_Military_Standing_Calm"

$DeclareSequence "coach_AimMatrix_Sniper_MilitaryZoomed_Injured_Standing"

$DeclareSequence "coach_AimMatrix_Sniper_Military_Injured_Standing"

$DeclareSequence "coach_AimMatrix_Sniper_Military_Crouching"

$DeclareSequence "coach_AimMatrix_Sniper_MilitaryZoomed_Crouching"

$DeclareSequence "coach_AimMatrix_Melee_Shove_Rifle_Standing"

$DeclareSequence "gambler_aimmatrix_fryingpan_injured_standing"

$DeclareSequence "NamVet_AimMatrix_M2HT_Standing"

$DeclareSequence "NamVet_AimMatrix_Frying_Pan_Standing_Calm"

$DeclareSequence "pour_gascan"

$DeclareSequence "Reload_Standing_grenade_launcher_layer"

$DeclareSequence "Reload_Standing_grendade_launcher"

$DeclareSequence "jump_Frying_Pan_layer"

$DeclareSequence "Jump_Frying_Pan_01"

$DeclareSequence "c4m1_intro_coach"

$DeclareSequence "c2m1_intro_coach"

$DeclareSequence "c5m1_intro_coach"

$DeclareSequence "c1m1_intro_coach"

$DeclareSequence "dlc1_intro_male_idle"

$DeclareSequence "dlc1_intro_male_leanup"

$DeclareSequence "dlc1_intro_male_leanleft"

$DeclareSequence "dlc1_intro_male_headnod"

$DeclareSequence "dlc1_intro_male_handflipR"

$DeclareSequence "dlc1_finaleintro_francis_idle"

$DeclareSequence "dlc1_finaleintro_francis_weight_shift_hold"

$DeclareSequence "dlc1_finaleintro_francis_idle_looking"

$DeclareSequence "dlc1_finaleintro_francis_idle_extra_noise"

$DeclareSequence "dlc1_finaleintro_francis_idle_extra_noise_02"

$DeclareSequence "dlc1_finaleintro_francis_gesture01"

$DeclareSequence "dlc1_finaleintro_francis_gesture02"

$DeclareSequence "dlc1_finaleintro_francis_gesture03"

$DeclareSequence "dlc1_finaleintro_francis_gesture04"

$DeclareSequence "dlc1_finaleintro_francis_gesture05"

$DeclareSequence "dlc1_finaleintro_francis_gesture06"

$DeclareSequence "dlc1_finaleintro_francis_gesture07"

$DeclareSequence "dlc1_finaleintro_francis_looklouis"

$DeclareSequence "dlc1_finaleintro_francis_looklouis_slow"

$DeclareSequence "dlc1_finaleintro_francis_looklouis2"

$DeclareSequence "dlc1_finaleintro_francis_looklouis2_slow"

$DeclareSequence "dlc1_finaleintro_francis_lookzoey"

$DeclareSequence "dlc1_finaleintro_francis_lookzoey_slow"

$DeclareSequence "dlc1_finaleintro_francis_lookzoey2"

$DeclareSequence "dlc1_finaleintro_francis_lookzoey2_slow"

$DeclareSequence "dlc1_finaleintro_francis_hello_rochelle"

$DeclareSequence "dlc1_finaleintro_francis_I_am_a_cop"

$DeclareSequence "dlc1_finaleintro_francis_ten_four"

$DeclareSequence "dlc1_finaleintro_francis_Yesnod"

$DeclareSequence "dlc1_finaleintro_francis_Ehhhhharmsout"

$DeclareSequence "dlc1_finaleintro_francis_16_beenthinkin"

$DeclareSequence "dlc1_finaleintro_francis_16_lookbrother"

$DeclareSequence "dlc1_finaleintro_francis_NiceRideWav"

$DeclareSequence "dlc1_finaleintro_francis_HowSheHandleWav"

$DeclareSequence "dlc1_finaleintro_francis_BikeManWav"

$DeclareSequence "dlc1_finaleintro_francis_GoodLuckWithTahtWav"

$DeclareSequence "dlc1_finaleintro_francis_headshake"

$DeclareSequence "dlc1_finaleintro_francis_you_hate_stuff_too"

$DeclareSequence "dlc1_finaleintro_francis_headnod"

$DeclareSequence "dlc1_finaleintro_francis_small_take"

$DeclareSequence "dlc1_finaleintro_francis_you_like_vests"

$DeclareSequence "dlc1_finaleintro_francis_even_smaller_take"

$DeclareSequence "dlc1_finaleintro_francis_hello_rochelle_alt"

$DeclareSequence "dlc1_finaleintro_francis_you_hate_stuff_too_slower"

$DeclareSequence "dlc1_finaleintro_francis_gesture09"

$DeclareSequence "dlc1_finaleintro_francis_all_yer_crying"

$DeclareSequence "dlc1_finaleintro_francis_head_shake_at_louis"

$DeclareSequence "dlc1_finaleintro_francis_hey_all_right"

$DeclareSequence "dlc1_finaleintro_francis_Yesnod2"

$DeclareSequence "dlc1_finaleintro_francis_TacoDogX2Wav"

$DeclareSequence "dlc1_finaleintro_francis_Lean"

$DeclareSequence "dlc1_finaleintro_francis_salute"

$DeclareSequence "dlc1_finaleintro_louis_idle"

$DeclareSequence "dlc1_finaleintro_louis_wave"

$DeclareSequence "dlc1_finaleintro_louis_lookfrancis"

$DeclareSequence "dlc1_finaleintro_louis_nod"

$DeclareSequence "dlc1_finaleintro_louis_lookfrancis2"

$DeclareSequence "dlc1_finaleintro_louis_lookzoey2"

$DeclareSequence "dlc1_finaleintro_louis_wavesmall"

$DeclareSequence "dlc1_finaleintro_louis_headshakeno2"

$DeclareSequence "dlc1_finaleintro_louis_headshakeno"

$DeclareSequence "dlc1_finaleintro_louis_Lookoff"

$DeclareSequence "dlc1_finaleintro_louis_giggle"

$DeclareSequence "dlc1_finaleintro_louis_arm_gesture"

$DeclareSequence "dlc1_finaleintro_louis_speech01"

$DeclareSequence "dlc1_finaleintro_louis_headnod"

$DeclareSequence "dlc1_finaleintro_louis_headshake"

$DeclareSequence "dlc1_finaleintro_louis_lookfrancis_long"

$DeclareSequence "dlc1_finaleintro_louis_GotoGeneratorWav"

$DeclareSequence "dlc1_finaleintro_louis_HeyYouMadeItWav"

$DeclareSequence "dlc1_finaleintro_louis_you_made_it"

$DeclareSequence "dlc1_finaleintro_louis_where_you_heading"

$DeclareSequence "dlc1_finaleintro_louis_nah_better_not"

$DeclareSequence "dlc1_finaleintro_louis_take_care_of_the_rest"

$DeclareSequence "dlc1_outro_francis"

$DeclareSequence "dlc1_outro_louis"

$DeclareSequence "Idle_Fall_From_charger"

$DeclareSequence "Charger_pounded"

$DeclareSequence "Charger_pounded_down"

$DeclareSequence "Charger_pounded_north"

$DeclareSequence "Charger_pounded_up"

$DeclareSequence "Charger_pounded_incap"

$DeclareSequence "GetUpFrom_Charger"

$DeclareSequence "IncapFrom_Charger"

$DeclareSequence "Hit_by_Charger"

$DeclareSequence "Charger_Carried"

$DeclareSequence "Charger_Slammed_Wall"

$DeclareSequence "Charger_Slammed_Ground"

$DeclareSequence "survivor_ridden_upper"

$DeclareSequence "survivor_ridden_lower_walk"

$DeclareSequence "coach_adrenaline_use"

$DeclareSequence "Defibrillate_Incap_Standing"

$DeclareSequence "Defibrillate_Incap_Crouching"

$DeclareSequence "Die_Standing"

$DeclareSequence "Die_Incap"

$DeclareSequence "Defib_Revive"

$DeclareSequence "Defib_jolt"

$DeclareSequence "coach_AimMatrix_chainsaw_Standing_layer"

$DeclareSequence "coach_AimMatrix_chainsaw_Standing_arms"

$DeclareSequence "Idle_Standing_chainsaw"

$DeclareSequence "Idle_Crouching_chainsaw"

$DeclareSequence "coach_AimMatrix_chainsaw_Standing_Calm_layer"

$DeclareSequence "coach_AimMatrix_chainsaw_Standing_Calm_arms"

$DeclareSequence "Idle_Calm_chainsaw"

$DeclareSequence "coach_AimMatrix_chainsaw_Injured_Standing_layer"

$DeclareSequence "coach_AimMatrix_chainsaw_Injured_Standing_arms"

$DeclareSequence "Idle_Injured_chainsaw"

$DeclareSequence "CrouchWalkN_chainsaw_layer"

$DeclareSequence "CrouchWalkN_chainsaw_arms"

$DeclareSequence "CrouchWalk_chainsaw"

$DeclareSequence "WalkN_chainsaw_layer"

$DeclareSequence "WalkN_chainsaw_arms"

$DeclareSequence "Walk_chainsaw"

$DeclareSequence "RunN_chainsaw_layer"

$DeclareSequence "RunN_chainsaw_arms"

$DeclareSequence "Run_chainsaw"

$DeclareSequence "LimpWalk_CHAINSAW"

$DeclareSequence "LimpRun_chainsaw"

$DeclareSequence "coach_AimMatrix_chainsaw_Standing"

$DeclareSequence "coach_AimMatrix_chainsaw_Crouching"

$DeclareSequence "coach_AimMatrix_chainsaw_Injured_Standing"

$DeclareSequence "Idle_Attack_Chainsaw"

$DeclareSequence "jump_chainsaw_layer"

$DeclareSequence "Jump_chainsaw_01"

$DeclareSequence "chainsaw_startup"

$DeclareSequence "chainsaw_rev"

$DeclareSequence "chainsaw_attack"

$DeclareSequence "Idle_Standing_guitar"

$DeclareSequence "Idle_Crouching_guitar"

$DeclareSequence "Idle_Calm_Guitar"

$DeclareSequence "idle_injured_guitar"

$DeclareSequence "WalkN_guitar_layer"

$DeclareSequence "WalkN_guitar_arms"

$DeclareSequence "Walk_guitar"

$DeclareSequence "CrouchWalkN_guitar_layer"

$DeclareSequence "CrouchWalkN_guitar_arms"

$DeclareSequence "CrouchWalk_guitar"

$DeclareSequence "RunN_GUITAR_layer"

$DeclareSequence "RunN_GUITAR_arms"

$DeclareSequence "Run_GUITAR"

$DeclareSequence "LimpWalk_GUITAR"

$DeclareSequence "LimpRun_GUITAR"

$DeclareSequence "coach_AimMatrix_GUITAR_Standing"

$DeclareSequence "coach_AimMatrix_GUITAR_Crouching"

$DeclareSequence "coach_AimMatrix_GUITAR_Injured_Standing"

$DeclareSequence "jump_GUITAR_layer"

$DeclareSequence "Jump_GUITAR_01"

$DeclareSequence "idle_standing_gnome"

$DeclareSequence "idle_crouching_gnome"

$DeclareSequence "idle_calm_gnome"

$DeclareSequence "Idle_Injured_gnome"

$DeclareSequence "CrouchWalkN_gnome_layer"

$DeclareSequence "CrouchWalkN_gnome_arms"

$DeclareSequence "CrouchWalk_gnome"

$DeclareSequence "WalkN_gnome_layer"

$DeclareSequence "WalkN_gnome_arms"

$DeclareSequence "Walk_gnome"

$DeclareSequence "RunN_gnome_layer"

$DeclareSequence "RunN_gnome_arms"

$DeclareSequence "Run_gnome"

$DeclareSequence "CalmWalkN_gnome_layer"

$DeclareSequence "CalmWalkN_gnome_arms"

$DeclareSequence "CalmWalk_gnome"

$DeclareSequence "CalmRunN_gnome_layer"

$DeclareSequence "CalmRunN_gnome_arms"

$DeclareSequence "CalmRun_gnome"

$DeclareSequence "LimpWalk_gnome"

$DeclareSequence "LimpRun_gnome"

$DeclareSequence "Coach_AimMatrix_gnome_Standing"

$DeclareSequence "Coach_AimMatrix_gnome_Crouching"

$DeclareSequence "Coach_AimMatrix_gnome_Injured"

$DeclareSequence "jump_gnome_layer"

$DeclareSequence "jump_gnome_gesture"

$DeclareSequence "jump_gnome_gesture_aim"

$DeclareSequence "Jump_gnome_01"

$DeclareSequence "Jump_gnome_02"

$DeclareSequence "axe_swing_ne_w_layer"

$DeclareSequence "axe_swing_ne_w_idle"

$DeclareSequence "axe_swing_strong_layer"

$DeclareSequence "axe_swing_layer_2"

$DeclareSequence "axe_secondary_attack"

$DeclareSequence "AXE_primary_attack_reverse"

$DeclareSequence "AXE_primary_attack_reverse_idle"

$DeclareSequence "Frying_Pan_swing_N_S_layer"

$DeclareSequence "Frying_Pan_swing_N_S_idle"

$DeclareSequence "Frying_Pan_secondary_attack"

$DeclareSequence "Frying_Pan_strong_attack"

$DeclareSequence "Frying_Pan_strong_attack_idle"

$DeclareSequence "Frying_Pan_swing_NE_SW_layer"

$DeclareSequence "Frying_Pan_swing_NE_SW_idle"

$DeclareSequence "bat_swing_ne_w_layer"

$DeclareSequence "bat_swing_ne_w_idle"

$DeclareSequence "bat_swing_w2e_layer"

$DeclareSequence "bat_swing_w2e_idle"

$DeclareSequence "bat_secondary_attack"

$DeclareSequence "guitar_primary_attack_LAYER"

$DeclareSequence "guitar_primary_attack"

$DeclareSequence "guitar_primary_attack02_LAYER"

$DeclareSequence "guitar_primary_attack02"

$DeclareSequence "guitar_secondary_attack_LAYER"

$DeclareSequence "guitar_secondary_attack"

$DeclareSequence "use_ammopack"

$DeclareSequence "crouch_use_ammopack"

$DeclareSequence "melee_sweep_gnome"

$DeclareSequence "melee_sweep_chainsaw"

$DeclareSequence "use_cola"

$DeclareSequence "Coach_AimMatrix_FirstAidKit_Standing"

$DeclareSequence "melee_sweep_FirstAidKit"

$DeclareSequence "melee_sweep_cola"

$DeclareSequence "melee_sweep_defibrillator"

$DeclareSequence "melee_sweep_ammopack"

$DeclareSequence "katana_swing_e2w_layer"

$DeclareSequence "katana_swing_e2w_idle"

$DeclareSequence "katana_swing_w2e_layer"

$DeclareSequence "katana_swing_w2e_idle"

$DeclareSequence "Shoved_Backward"

$DeclareSequence "Shoved_Forward"

$DeclareSequence "Shoved_Rightward"

$DeclareSequence "Shoved_Leftward"

$DeclareSequence "Shoved_Backward_Melee"

$DeclareSequence "Shoved_Forward_Melee"

$DeclareSequence "Shoved_Rightward_Melee"

$DeclareSequence "Shoved_Leftward_Melee"

$DeclareSequence "Shoved_Backward_bat"

$DeclareSequence "Shoved_Forward_bat"

$DeclareSequence "Shoved_Rightward_bat"

$DeclareSequence "Shoved_Leftward_bat"

$DeclareSequence "Shoved_Backward_chainsaw"

$DeclareSequence "Shoved_Forward_chainsaw"

$DeclareSequence "Shoved_Rightward_chainsaw"

$DeclareSequence "Shoved_Leftward_chainsaw"

$DeclareSequence "namvet_gesture_pointLeftinDelta"

$DeclareSequence "namvet_gesture_pointLeftinFrameArms"

$DeclareSequence "namvet_gesture_pointLeftinFrameSpine"

$DeclareSequence "namvet_gesture_pointLeftCoreDelta"

$DeclareSequence "namvet_gesture_pointLeftOutFrameArms"

$DeclareSequence "namvet_gesture_pointLeftOutFrameSpine"

$DeclareSequence "namvet_gesture_pointLeftoutDelta"

$DeclareSequence "namvet_gesture_pointLeft"

$DeclareSequence "namvet_gesture_pointLeft_quickinDelta"

$DeclareSequence "namvet_gesture_pointLeft_quickinFrameArms"

$DeclareSequence "namvet_gesture_pointLeft_quickinFrameSpine"

$DeclareSequence "namvet_gesture_pointLeft_quickCoreDelta"

$DeclareSequence "namvet_gesture_pointLeft_quickOutFrameArms"

$DeclareSequence "namvet_gesture_pointLeft_quickOutFrameSpine"

$DeclareSequence "namvet_gesture_pointLeft_quickoutDelta"

$DeclareSequence "namvet_gesture_pointLeft_quick"

$DeclareSequence "namvet_gesture_gogoinDelta"

$DeclareSequence "namvet_gesture_gogoinFrameArms"

$DeclareSequence "namvet_gesture_gogoinFrameSpine"

$DeclareSequence "namvet_gesture_gogoCoreDelta"

$DeclareSequence "namvet_gesture_gogoOutFrameArms"

$DeclareSequence "namvet_gesture_gogoOutFrameSpine"

$DeclareSequence "namvet_gesture_gogooutDelta"

$DeclareSequence "namvet_gesture_gogo"

$DeclareSequence "namvet_gesture_waveinDelta"

$DeclareSequence "namvet_gesture_waveinFrameArms"

$DeclareSequence "namvet_gesture_waveinFrameSpine"

$DeclareSequence "namvet_gesture_waveCoreDelta"

$DeclareSequence "namvet_gesture_waveOutFrameArms"

$DeclareSequence "namvet_gesture_waveOutFrameSpine"

$DeclareSequence "namvet_gesture_waveoutDelta"

$DeclareSequence "namvet_gesture_wave"

$DeclareSequence "namVet_head_no"

$DeclareSequence "namvet_gesture_head_noddefault"

$DeclareSequence "namvet_gesture_head_nodapexDelta"

$DeclareSequence "namvet_gesture_head_nodloopDelta"

$DeclareSequence "namvet_gesture_head_nod"

$DeclareSequence "namvet_gesture_head_twistLeftdefault"

$DeclareSequence "namvet_gesture_head_twistLeftapexDelta"

$DeclareSequence "namvet_gesture_head_twistLeftloopDelta"

$DeclareSequence "namvet_gesture_head_twistLeft"

$DeclareSequence "namvet_gesture_coughinDelta"

$DeclareSequence "namvet_gesture_coughinFrameArms"

$DeclareSequence "namvet_gesture_coughinFrameSpine"

$DeclareSequence "namvet_gesture_coughCoreDelta"

$DeclareSequence "namvet_gesture_coughOutFrameArms"

$DeclareSequence "namvet_gesture_coughOutFrameSpine"

$DeclareSequence "namvet_gesture_coughoutDelta"

$DeclareSequence "namvet_gesture_cough"

$DeclareSequence "namvet_gesture_cough1inDelta"

$DeclareSequence "namvet_gesture_cough1inFrameArms"

$DeclareSequence "namvet_gesture_cough1inFrameSpine"

$DeclareSequence "namvet_gesture_cough1CoreDelta"

$DeclareSequence "namvet_gesture_cough1OutFrameArms"

$DeclareSequence "namvet_gesture_cough1OutFrameSpine"

$DeclareSequence "namvet_gesture_cough1outDelta"

$DeclareSequence "namvet_gesture_cough1"

$DeclareSequence "namvet_gesture_cough2inDelta"

$DeclareSequence "namvet_gesture_cough2inFrameArms"

$DeclareSequence "namvet_gesture_cough2inFrameSpine"

$DeclareSequence "namvet_gesture_cough2CoreDelta"

$DeclareSequence "namvet_gesture_cough2OutFrameArms"

$DeclareSequence "namvet_gesture_cough2OutFrameSpine"

$DeclareSequence "namvet_gesture_cough2outDelta"

$DeclareSequence "namvet_gesture_cough2"

$DeclareSequence "namvet_gesture_cough3inDelta"

$DeclareSequence "namvet_gesture_cough3inFrameArms"

$DeclareSequence "namvet_gesture_cough3inFrameSpine"

$DeclareSequence "namvet_gesture_cough3CoreDelta"

$DeclareSequence "namvet_gesture_cough3OutFrameArms"

$DeclareSequence "namvet_gesture_cough3OutFrameSpine"

$DeclareSequence "namvet_gesture_cough3outDelta"

$DeclareSequence "namvet_gesture_cough3"

$DeclareSequence "namvet_gesture_vomit01inDelta"

$DeclareSequence "namvet_gesture_vomit01inFrameArms"

$DeclareSequence "namvet_gesture_vomit01inFrameSpine"

$DeclareSequence "namvet_gesture_vomit01CoreDelta"

$DeclareSequence "namvet_gesture_vomit01OutFrameArms"

$DeclareSequence "namvet_gesture_vomit01OutFrameSpine"

$DeclareSequence "namvet_gesture_vomit01outDelta"

$DeclareSequence "namvet_gesture_vomit01"

$DeclareSequence "namvet_gesture_head_downdefault"

$DeclareSequence "namvet_gesture_head_downapexDelta"

$DeclareSequence "namvet_gesture_head_downloopDelta"

$DeclareSequence "namvet_gesture_head_down"

$DeclareSequence "namvet_gesture_head_yesdefault"

$DeclareSequence "namvet_gesture_head_yesapexDelta"

$DeclareSequence "namvet_gesture_head_yesloopDelta"

$DeclareSequence "namvet_gesture_head_yes"

$DeclareSequence "g_Idle_Intro_CalminDelta"

$DeclareSequence "g_Idle_Intro_CalminFrameArms"

$DeclareSequence "g_Idle_Intro_CalminFrameSpine"

$DeclareSequence "g_Idle_Intro_CalmCoreDelta"

$DeclareSequence "g_Idle_Intro_CalmOutFrameArms"

$DeclareSequence "g_Idle_Intro_CalmOutFrameSpine"

$DeclareSequence "g_Idle_Intro_CalmoutDelta"

$DeclareSequence "g_Idle_Intro_Calm"

$DeclareSequence "g_Namvet_Intro_WaveinDelta"

$DeclareSequence "g_Namvet_Intro_WaveinFrameArms"

$DeclareSequence "g_Namvet_Intro_WaveinFrameSpine"

$DeclareSequence "g_Namvet_Intro_WaveCoreDelta"

$DeclareSequence "g_Namvet_Intro_WaveOutFrameArms"

$DeclareSequence "g_Namvet_Intro_WaveOutFrameSpine"

$DeclareSequence "g_Namvet_Intro_WaveoutDelta"

$DeclareSequence "g_Namvet_Intro_Wave"

$IncludeModel "survivors/anim_Biker.mdl"
$IncludeModel "survivors/gestures_biker.mdl"
//$IncludeModel "survivors/gestures_coach.mdl" // coach,gambler,mechanic,producer
//$IncludeModel "survivors/anim_mechanic.mdl" // mechanic
$IncludeModel "survivors/anim_TeenAngst.mdl" // TeenAngst
$IncludeModel "survivors/gestures_TeenAngst.mdl" // TeenAngst

//$IncludeModel "survivors/anim_gambler.mdl" // gambler
//$IncludeModel "survivors/anim_producer.mdl" // producer
// $IncludeModel "survivors/anim_coach.mdl" // coach