// Created by Crowbar-Starfelll 1.0

$ModelName "survivors/test/survivor_TeenAngst.mdl"

$SurfaceProp "flesh"

$Contents "solid"

$IllumPosition 0 -0.861 33.401

$EyePosition 0 0 60

$MaxEyeDeflection 30

$ForcePhonemeCrossFade

$AmbientBoost

$MostlyOpaque

$CDMaterials "models\survivors\TeenAngst\"
$CDMaterials "models\survivors\"
$CDMaterials ""

$TextureGroup "skinfamilies"
{
	{ "zoey_head"    "zoey_color"    }
	{ "zoey_head_it" "zoey_color_it" }
}

$Attachment "eyes" "ValveBiped.Bip01_Head1" 3.04 -2.42 -0.01 rotate 0 -89.37 -90
$Attachment "mouth" "ValveBiped.Bip01_Head1" 0.8 -5.8 -0.15 rotate 0 -80 -90
$Attachment "legR" "ValveBiped.Bip01_R_Thigh" 0 0 0 rotate 0 0 0
$Attachment "legR_B" "ValveBiped.attachment_bandage_legR" 0 0 0 rotate -90 -90 0
$Attachment "molotov" "ValveBiped.Bip01_Pelvis" 6.25 3.04 -2.85 rotate 26.07 5.23 -89.64
$Attachment "pills" "ValveBiped.Bip01_Pelvis" -5.11 -0.49 3.22 rotate -0.71 177.48 91.57
$Attachment "grenade" "ValveBiped.Bip01_Pelvis" 5.55 4.03 2.44 rotate 0 0 -90
$Attachment "pistol" "ValveBiped.jiggle_holster" -2.18 -2.22 -3.74 rotate -67.79 6.17 -115.72
$Attachment "primary" "ValveBiped.Bip01_Spine4" 4.21 -2.88 -2.7 rotate -15.77 -173.22 167.93
$Attachment "medkit" "ValveBiped.Bip01_Spine4" -0.85 -5.42 -2.32 rotate 5.03 88.01 0
$Attachment "R_shoulderBladeAim" "ValveBiped.Bip01_Spine" 0 0 0 rotate 0 0 0
$Attachment "L_shoulderBladeAim" "ValveBiped.Bip01_Spine" 0 0 0 rotate 0 0 0
$Attachment "melee" "ValveBiped.Bip01_Spine4" 2.64 -4.1 4.45 rotate 24 175 97
$Attachment "lfoot" "ValveBiped.Bip01_L_Foot" 0 5 0 rotate 0 0 0
$Attachment "rfoot" "ValveBiped.Bip01_R_Foot" 0 5 0 rotate 0 0 0
$Attachment "muzzle_flash" "ValveBiped.Bip01_L_Hand" 0 0 0 rotate 0 0 0
$Attachment "survivor_neck" "ValveBiped.Bip01_Neck1" 0 0 0 rotate 0 0 0
$Attachment "forward" "ValveBiped.forward" 0 0 0 rotate 0 0 0
$Attachment "bleedout" "ValveBiped.Bip01_Pelvis" 9.5 10 5 rotate 0 0 0
$Attachment "survivor_light" "ValveBiped.Bip01_Spine2" 6 24 0 rotate 0 0 0
$Attachment "legL_B" "ValveBiped.attachment_bandage_legL" 0 0 0 rotate -90 -90 0
$Attachment "armL_B" "ValveBiped.attachment_bandage_armL" 0 0 0 rotate -90 -90 0
$Attachment "armL_T" "ValveBiped.attachment_armL_T" 0 0 0 rotate -90 -90 0
$Attachment "armR_T" "ValveBiped.attachment_armR_T" 0 0 0 rotate -90 -90 0
$Attachment "armL" "ValveBiped.Bip01_L_Forearm" 0 0 0 rotate 0 0 0
$Attachment "legL" "ValveBiped.Bip01_L_Calf" 0 0 0 rotate 0 0 0
$Attachment "thighL" "ValveBiped.Bip01_L_Thigh" 0 0 0 rotate 0 0 0
$Attachment "spine" "ValveBiped.Bip01_Spine" 0 0 0 rotate -90 -90 0

$CBox 0 0 0 0 0 0

$BBox -13 -13 0 13 13 72

$HBoxSet "L4D"
$HBox 3 "ValveBiped.Bip01_Pelvis" -6 -4.5 -4.5 6 4.5 4.5
$HBox 6 "ValveBiped.Bip01_L_Thigh" 5 -3.4 -2.85 19 2.6 2.15
$HBox 6 "ValveBiped.Bip01_L_Calf" 0.5 -1.5 -2 19.5 2.5 2
$HBox 6 "ValveBiped.Bip01_L_Toe0" -3.5 -0.5 -1.35 1.5 1.5 2.45
$HBox 7 "ValveBiped.Bip01_R_Thigh" 5 -3.4 -2.85 19 2.6 2.15
$HBox 7 "ValveBiped.Bip01_R_Calf" 0.5 -1.5 -2 19.5 2.5 2
$HBox 7 "ValveBiped.Bip01_R_Toe0" -3.5 -0.5 -1.35 1.5 1.5 2.45
$HBox 3 "ValveBiped.Bip01_Spine1" -5 -3 -5.5 5 5 5.5
$HBox 2 "ValveBiped.Bip01_Spine2" -2.5 -3.25 -5.75 11.5 5.25 5.75
$HBox 1 "ValveBiped.Bip01_Neck1" 0 -2 -2 4 2 2
$HBox 1 "ValveBiped.Bip01_Head1" -0.8 -3.8 -3.05 7.2 4.2 2.45
$HBox 4 "ValveBiped.Bip01_L_UpperArm" 0 -1.9 -1.8 11 1.7 1.8
$HBox 4 "ValveBiped.Bip01_L_Forearm" 0.5 -1.5 -1.5 11.5 1.5 1.5
$HBox 4 "ValveBiped.Bip01_L_Hand" 1.06 -1.29 -2.15 5.56 0.41 1.05
$HBox 5 "ValveBiped.Bip01_R_UpperArm" 0 -1.9 -1.8 11 1.7 1.8
$HBox 5 "ValveBiped.Bip01_R_Forearm" 0.5 -1.5 -1.5 11.5 1.5 1.5
$HBox 5 "ValveBiped.Bip01_R_Hand" 1.06 -1.29 -2.15 5.56 0.41 1.05
$SkipBoneInBBox

$DefineBone "ValveBiped.Bip01_Pelvis" "" 0 -1.442119 35.350025 0 0 89.999982 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Thigh" "ValveBiped.Bip01_Pelvis" 3.455587 0 0 1.772617 -92.012497 -89.999982 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Calf" "ValveBiped.Bip01_L_Thigh" 16.572346 0 0 0 0.566827 0 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Foot" "ValveBiped.Bip01_L_Calf" 16.265829 0 0 -7.509586 -73.645258 -0.092475 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Toe0" "ValveBiped.Bip01_L_Foot" 5.046457 0 0 -1.076992 -18.787914 0.56803 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Thigh" "ValveBiped.Bip01_Pelvis" -3.455587 0 0 1.772617 -87.987528 -89.999982 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Calf" "ValveBiped.Bip01_R_Thigh" 16.572346 0 0 0 0.566827 0 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Foot" "ValveBiped.Bip01_R_Calf" 16.265831 0 0 7.509586 -73.645258 0.760544 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Toe0" "ValveBiped.Bip01_R_Foot" 5.046457 0 0 0.861731 -18.798634 -5.743558 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_Spine" "ValveBiped.Bip01_Pelvis" 0 3.703728 0.293189 0.746106 89.999982 89.999982 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_Spine1" "ValveBiped.Bip01_Spine" 3.307846 0 0 0 -8.256092 0 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_Spine2" "ValveBiped.Bip01_Spine1" 3.297962 0 0 0 -7.686283 0 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_Spine4" "ValveBiped.Bip01_Spine2" 6.040985 0 0 0 18.68696 0 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_Neck1" "ValveBiped.Bip01_Spine4" 5.065758 0 0 0 18.767061 179.999855 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_Head1" "ValveBiped.Bip01_Neck1" 3.993755 0 0 -0.000057 20.137751 0 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Clavicle" "ValveBiped.Bip01_Spine4" 3.815876 1.385489 1.5 -60.013717 -143.407731 47.713806 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_UpperArm" "ValveBiped.Bip01_L_Clavicle" 4.327093 0.000004 0 -8.799196 -50.70367 -71.244727 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Forearm" "ValveBiped.Bip01_L_UpperArm" 11.105114 0 0 0.000003 -7.825969 0.000001 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Hand" "ValveBiped.Bip01_L_Forearm" 9.862099 -0.000011 -0.000031 9.512935 4.404275 70.35573 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Finger4" "ValveBiped.Bip01_L_Hand" 2.641094 0.214619 -1.073586 10.920007 -11.807972 19.688432 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Finger41" "ValveBiped.Bip01_L_Finger4" 1.361605 -0.000002 0 -3.240243 -30.919372 -1.938946 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Finger42" "ValveBiped.Bip01_L_Finger41" 0.779602 0.000002 0 -7.106905 -17.440943 -2.225943 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Finger3" "ValveBiped.Bip01_L_Hand" 2.908712 0.221762 -0.431868 3.695296 -13.818138 18.088158 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Finger31" "ValveBiped.Bip01_L_Finger3" 1.597527 0.000001 0 -2.513905 -24.903143 -1.166545 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Finger32" "ValveBiped.Bip01_L_Finger31" 0.91268 0.000001 0 0.475444 -17.472273 0.149652 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Finger2" "ValveBiped.Bip01_L_Hand" 3.26545 0.050007 0.415744 5.238157 -10.578232 18.511686 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Finger21" "ValveBiped.Bip01_L_Finger2" 1.86047 0 0 -3.682342 -38.801444 -2.956181 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Finger22" "ValveBiped.Bip01_L_Finger21" 1.061481 -0.000001 0 1.690396 -7.861432 0.23336 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Finger1" "ValveBiped.Bip01_L_Hand" 3.340382 -0.242393 1.285012 3.584946 -9.395935 18.251853 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Finger11" "ValveBiped.Bip01_L_Finger1" 1.550753 0.000001 0 4.354427 -39.142243 3.536178 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Finger12" "ValveBiped.Bip01_L_Finger11" 0.904888 0.000001 0 1.507801 -3.604421 0.094995 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Finger0" "ValveBiped.Bip01_L_Hand" 1.219385 -1.06386 0.837143 -18.58956 -14.661875 108.429629 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Finger01" "ValveBiped.Bip01_L_Finger0" 1.496971 -0.000002 -0.000001 -5.43038 -19.136452 0.000002 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Finger02" "ValveBiped.Bip01_L_Finger01" 1.100086 0 0 -2.329993 16.368371 0.000002 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Clavicle" "ValveBiped.Bip01_Spine4" 3.815876 1.385489 -1.5 60.013717 -143.407731 -52.105929 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_UpperArm" "ValveBiped.Bip01_R_Clavicle" 4.327089 -0.000004 0 12.186296 -50.185372 74.088906 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Forearm" "ValveBiped.Bip01_R_UpperArm" 11.105106 0 0.000004 -0.000003 -7.825976 0.000001 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Hand" "ValveBiped.Bip01_R_Forearm" 9.86208 -0.000007 0.000017 -9.513105 4.404153 -70.517468 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Finger4" "ValveBiped.Bip01_R_Hand" 2.641111 0.211586 1.074188 -10.92012 -11.807802 -19.526623 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Finger41" "ValveBiped.Bip01_R_Finger4" 1.361601 0 0 3.240245 -30.919382 1.938947 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Finger42" "ValveBiped.Bip01_R_Finger41" 0.779604 0.000001 0 7.106911 -17.440956 2.225943 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Finger3" "ValveBiped.Bip01_R_Hand" 2.90873 0.220541 0.432493 -3.695405 -13.817909 -17.926415 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Finger31" "ValveBiped.Bip01_R_Finger3" 1.597527 0 0 2.513912 -24.903145 1.16654 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Finger32" "ValveBiped.Bip01_R_Finger31" 0.912678 0 0 -0.47544 -17.47228 -0.149659 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Finger2" "ValveBiped.Bip01_R_Hand" 3.265471 0.051184 -0.4156 -5.238268 -10.578062 -18.349892 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Finger21" "ValveBiped.Bip01_R_Finger2" 1.86047 0 0 3.68234 -38.801447 2.956173 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Finger22" "ValveBiped.Bip01_R_Finger21" 1.061485 0 0 -1.6904 -7.861441 -0.233369 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Finger1" "ValveBiped.Bip01_R_Hand" 3.340403 -0.238762 -1.285691 -3.585054 -9.395706 -18.09005 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Finger11" "ValveBiped.Bip01_R_Finger1" 1.550755 0 0 -4.354425 -39.142247 -3.536182 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Finger12" "ValveBiped.Bip01_R_Finger11" 0.904886 0.000001 0 -1.507798 -3.604425 -0.094998 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Finger0" "ValveBiped.Bip01_R_Hand" 1.21941 -1.061498 -0.840143 18.63042 -14.608936 -108.264434 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Finger01" "ValveBiped.Bip01_R_Finger0" 1.496971 0.000002 0 5.43038 -19.136443 0.000004 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Finger02" "ValveBiped.Bip01_R_Finger01" 1.100088 0 0 2.329992 16.368384 0.000004 0 0 0 0 0 0
$DefineBone "ValveBiped.jiggle_holster" "ValveBiped.Bip01_Pelvis" -7.117489 0.964596 -0.285143 -17.617416 -19.961571 99.911351 0 0 0 0 0 0
$DefineBone "ValveBiped.jiggy_hair_ponytail_01" "ValveBiped.Bip01_Head1" 2.745762 5.186402 -0.079196 -89.999852 -34.558278 0 0 0 0 0 0 0
$DefineBone "ValveBiped.jiggy_hair_ponytail_02" "ValveBiped.jiggy_hair_ponytail_01" -0.117863 -1.31617 3.221458 0 0 46.581071 0 0 0 0 0 0
$DefineBone "ValveBiped.jiggy_hair_lsideburn" "ValveBiped.Bip01_Head1" 3.339115 -0.255056 -2.865873 -0.000115 90.627827 -89.999982 0 0 0 0 0 0
$DefineBone "ValveBiped.jiggy_hair_lbang_01" "ValveBiped.Bip01_Head1" 5.423588 -2.821211 -1.367722 56.524118 53.16774 -135.834322 0 0 0 0 0 0
$DefineBone "ValveBiped.jiggy_hair_rbang" "ValveBiped.Bip01_Head1" 4.278461 -2.80242 2.057896 44.906814 -96.146032 81.805988 0 0 0 0 0 0
$DefineBone "ValveBiped.jiggy_hair_rsideburn" "ValveBiped.Bip01_Head1" 3.042778 -0.71361 2.741668 0.000113 -89.372137 89.999982 0 0 0 0 0 0
$DefineBone "ValveBiped.attachment_bandage_armL" "ValveBiped.Bip01_L_Forearm" 0 -0.000007 -0.000031 6.507312 7.122669 78.669798 0 0 0 0 0 0
$DefineBone "ValveBiped.attachment_bandage_legL" "ValveBiped.Bip01_L_Thigh" 0 0 0 -3.939487 -74.439527 -4.413494 0 0 0 0 0 0
$DefineBone "ValveBiped.attachment_bandage_legR" "ValveBiped.Bip01_R_Thigh" 7.054213 0 0 0 0 0 0 0 0 0 0 0
$DefineBone "ValveBiped.attachment_armL_T" "ValveBiped.Bip01_L_Forearm" 0 -0.000007 -0.000031 6.507312 7.122669 78.669798 0 0 0 0 0 0
$DefineBone "ValveBiped.attachment_armR_T" "ValveBiped.Bip01_R_Forearm" 0 -0.000007 -0.000031 6.507307 7.122666 78.669798 0 0 0 0 0 0
$DefineBone "ValveBiped.weapon_bone" "ValveBiped.Bip01_R_Hand" 2.856947 -1.536175 -0.97378 -15.616427 -90.427695 -86.009389 0 0 0 0 0 0
$DefineBone "ValveBiped.weapon_bone_Clip" "ValveBiped.weapon_bone" 0 0 10 0 -0.000001 0 0 0 0 0 0 0
$DefineBone "ValveBiped.L_weapon_bone" "ValveBiped.Bip01_L_Hand" 2.856899 -1.536201 -0.9738 -15.616428 -90.427695 -86.009389 0 0 0 0 0 0
$DefineBone "ValveBiped.forward" "ValveBiped.Bip01_Head1" 2 -3 0 0 -76 -90.000003 0 0 0 0 0 0
$DefineBone "ValveBiped.weapon_bone_extra" "ValveBiped.weapon_bone" 0.018896 0.665159 9.39588 0.000001 0.000001 0.000001 0 0 0 0 0 0
$DefineBone "ValveBiped.weapon_bone_Clip2" "ValveBiped.Bip01_L_Hand" 3.02821 -0.923409 -2.009452 -0.743371 90.942357 90.188256 0 0 0 0 0 0
$DefineBone "ValveBiped.weapon_bone_Clip2_Bullets" "ValveBiped.weapon_bone_Clip2" 0.116954 4.311606 0.061861 -0.000024 0.000012 0.000591 0 0 0 0 0 0
$DefineBone "ValveBiped.weapon_bolt_l" "ValveBiped.Bip01_L_Hand" 0 -0.000002 0 0.000002 -0.000003 0.000002 0 0 0 0 0 0
$DefineBone "ValveBiped.weapon_bone_Clip_Bullets" "ValveBiped.weapon_bone_Clip" 0 1 0.00001 0.000001 0.000001 0.000001 0 0 0 0 0 0
$DefineBone "ValveBiped.weapon_bolt" "ValveBiped.weapon_bone" -0.000001 0 0 0.000001 0.000001 0.000001 0 0 0 0 0 0
$DefineBone "ValveBiped.weapon_bolt_opposite" "ValveBiped.weapon_bone" -0.000001 0 0 0.000001 0.000001 0.000001 0 0 0 0 0 0
$DefineBone "ValveBiped.weapon_charger" "ValveBiped.weapon_bone" -0.000001 0 0 0.000001 0.000001 0.000001 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Knee" "ValveBiped.Bip01_L_Thigh" 16.559332 -0.019167 0.021773 0 2.275843 0 0 0 0 0 0 0
$DefineBone "ValveBiped.hlp_gluteus_L" "ValveBiped.Bip01_L_Thigh" -0.000004 0 0 0 0 0 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Knee" "ValveBiped.Bip01_R_Thigh" 16.514624 -0.017783 -0.020201 0 2.275672 0 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Ulna" "ValveBiped.Bip01_L_Forearm" 5.604149 0 0 0.000007 0.000001 -29.386465 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Wrist" "ValveBiped.Bip01_L_Forearm" 9.86903 -0.019478 0.023937 0.000007 0.000001 -56.453293 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Elbow" "ValveBiped.Bip01_L_UpperArm" 11.123051 0 0 0.000007 -17.244035 -0.000001 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_L_Bicep" "ValveBiped.Bip01_L_UpperArm" 5.560001 -0.7 -0.5 0.000005 -0.000002 -1.98228 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Wrist" "ValveBiped.Bip01_R_Forearm" 9.849226 0.015347 -0.007612 0.000012 -0.000004 56.417373 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Ulna" "ValveBiped.Bip01_R_Forearm" 5.604149 0 0 0.000012 -0.000004 29.381394 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Bicep" "ValveBiped.Bip01_R_UpperArm" 5.559994 -0.7 0.5 0.000012 0.000001 0 0 0 0 0 0 0
$DefineBone "ValveBiped.Bip01_R_Elbow" "ValveBiped.Bip01_R_UpperArm" 11.123047 0 0 0.000014 -17.243984 -0.000004 0 0 0 0 0 0

$BoneMerge "ValveBiped.Bip01_Pelvis"
$BoneMerge "ValveBiped.Bip01_Spine"
$BoneMerge "ValveBiped.Bip01_Spine1"
$BoneMerge "ValveBiped.Bip01_Spine2"
$BoneMerge "ValveBiped.Bip01_Spine4"
$BoneMerge "ValveBiped.Bip01_L_Clavicle"
$BoneMerge "ValveBiped.Bip01_L_UpperArm"
$BoneMerge "ValveBiped.Bip01_L_Forearm"
$BoneMerge "ValveBiped.Bip01_L_Hand"
$BoneMerge "ValveBiped.Bip01_L_Finger4"
$BoneMerge "ValveBiped.Bip01_L_Finger41"
$BoneMerge "ValveBiped.Bip01_L_Finger42"
$BoneMerge "ValveBiped.Bip01_L_Finger3"
$BoneMerge "ValveBiped.Bip01_L_Finger31"
$BoneMerge "ValveBiped.Bip01_L_Finger32"
$BoneMerge "ValveBiped.Bip01_L_Finger2"
$BoneMerge "ValveBiped.Bip01_L_Finger21"
$BoneMerge "ValveBiped.Bip01_L_Finger22"
$BoneMerge "ValveBiped.Bip01_L_Finger1"
$BoneMerge "ValveBiped.Bip01_L_Finger11"
$BoneMerge "ValveBiped.Bip01_L_Finger12"
$BoneMerge "ValveBiped.Bip01_L_Finger0"
$BoneMerge "ValveBiped.Bip01_L_Finger01"
$BoneMerge "ValveBiped.Bip01_L_Finger02"
$BoneMerge "ValveBiped.Bip01_R_Clavicle"
$BoneMerge "ValveBiped.Bip01_R_UpperArm"
$BoneMerge "ValveBiped.Bip01_R_Forearm"
$BoneMerge "ValveBiped.Bip01_R_Hand"
$BoneMerge "ValveBiped.Bip01_R_Finger4"
$BoneMerge "ValveBiped.Bip01_R_Finger41"
$BoneMerge "ValveBiped.Bip01_R_Finger42"
$BoneMerge "ValveBiped.Bip01_R_Finger3"
$BoneMerge "ValveBiped.Bip01_R_Finger31"
$BoneMerge "ValveBiped.Bip01_R_Finger32"
$BoneMerge "ValveBiped.Bip01_R_Finger2"
$BoneMerge "ValveBiped.Bip01_R_Finger21"
$BoneMerge "ValveBiped.Bip01_R_Finger22"
$BoneMerge "ValveBiped.Bip01_R_Finger1"
$BoneMerge "ValveBiped.Bip01_R_Finger11"
$BoneMerge "ValveBiped.Bip01_R_Finger12"
$BoneMerge "ValveBiped.Bip01_R_Finger0"
$BoneMerge "ValveBiped.Bip01_R_Finger01"
$BoneMerge "ValveBiped.Bip01_R_Finger02"
$BoneMerge "ValveBiped.weapon_bone"
$BoneMerge "ValveBiped.weapon_bone_Clip"
$BoneMerge "ValveBiped.L_weapon_bone"
$BoneMerge "ValveBiped.weapon_bone_extra"
$BoneMerge "ValveBiped.weapon_bone_Clip2"
$BoneMerge "ValveBiped.weapon_bone_Clip2_Bullets"
$BoneMerge "ValveBiped.weapon_bolt_l"
$BoneMerge "ValveBiped.weapon_bone_Clip_Bullets"
$BoneMerge "ValveBiped.weapon_bolt"
$BoneMerge "ValveBiped.weapon_bolt_opposite"
$BoneMerge "ValveBiped.weapon_charger"
$BoneMerge "ValveBiped.Bip01_L_Ulna"
$BoneMerge "ValveBiped.Bip01_L_Wrist"
$BoneMerge "ValveBiped.Bip01_R_Wrist"
$BoneMerge "ValveBiped.Bip01_R_Ulna"

$JiggleBone "ValveBiped.jiggle_holster"
{
	is_rigid
	{
		length 10
		tip_mass 1000
		pitch_constraint -3 3
		pitch_friction 0
		pitch_bounce 0
		yaw_constraint -74.999999 -15
		yaw_friction 0
		yaw_bounce 1
	}
}
$JiggleBone "ValveBiped.jiggy_hair_ponytail_01"
{
	is_rigid
	{
		length 5
		tip_mass 2000
		pitch_constraint 0 79.999998
		pitch_friction 0
		pitch_bounce 0
		yaw_constraint -50 50
		yaw_friction 0
		yaw_bounce 0
	}
}
$JiggleBone "ValveBiped.jiggy_hair_ponytail_02"
{
	is_rigid
	{
		length 5
		tip_mass 2000
		pitch_constraint 0 30.000001
		pitch_friction 5
		pitch_bounce 0
		yaw_constraint -50 50
		yaw_friction 0
		yaw_bounce 0
	}
}
$JiggleBone "ValveBiped.jiggy_hair_lsideburn"
{
	is_flexible
	{
		length 10
		tip_mass 100
		pitch_stiffness 100
		pitch_damping 5
		yaw_stiffness 100
		yaw_damping 5
		along_stiffness 100
		along_damping 0
		pitch_constraint 0 30.000001
		pitch_friction 5
		pitch_bounce 0
	}
}
$JiggleBone "ValveBiped.jiggy_hair_lbang_01"
{
	is_flexible
	{
		length 5
		tip_mass 1000
		pitch_stiffness 100
		pitch_damping 5
		yaw_stiffness 100
		yaw_damping 5
		along_stiffness 100
		along_damping 0
		pitch_constraint 0 79.999998
		pitch_friction 0
		pitch_bounce 0
	}
}
$JiggleBone "ValveBiped.jiggy_hair_rbang"
{
	is_flexible
	{
		length 10
		tip_mass 100
		pitch_stiffness 100
		pitch_damping 5
		yaw_stiffness 100
		yaw_damping 5
		along_stiffness 100
		along_damping 0
		pitch_constraint 0 30.000001
		pitch_friction 5
		pitch_bounce 0
	}
}
$JiggleBone "ValveBiped.jiggy_hair_rsideburn"
{
	is_flexible
	{
		length 10
		tip_mass 100
		pitch_stiffness 100
		pitch_damping 5
		yaw_stiffness 100
		yaw_damping 5
		along_stiffness 100
		along_damping 0
		pitch_constraint 0 30.000001
		pitch_friction 5
		pitch_bounce 0
	}
}

$PoseParameter "body_pitch" -90 90 loop 360
$PoseParameter "body_yaw" -90 90 loop 360
$PoseParameter "head_pitch" -90 90 loop 360
$PoseParameter "head_yaw" -90 90 loop 360

$IKChain "rhand" "ValveBiped.Bip01_R_Hand" knee 0.707 0.707 0
$IKChain "lhand" "ValveBiped.Bip01_L_Hand" knee 0.707 0.707 0
$IKChain "rfoot" "ValveBiped.Bip01_R_Foot" knee 0.707 -0.707 0
$IKChain "lfoot" "ValveBiped.Bip01_L_Foot" knee 0.707 -0.707 0
$IKChain "ikclip" "ValveBiped.weapon_bone_Clip" knee 0.707 -0.707 0

$IKAutoPlayLock "rfoot" 1 0.1
$IKAutoPlayLock "lfoot" 1 0.1

$Sequence "TeenAngst" {
	"survivor_teenangst_anims\TeenAngst.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 1
	ikrule "rfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 2
	ikrule "lfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 3
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 4
}

$Sequence "ragdoll" {
	"survivor_teenangst_anims\ragdoll.smd"
	activity "ACT_DIERAGDOLL" 1
	fadein 0.2
	fadeout 0.2
	fps 30
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 1 1 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 1 1 target 1
	ikrule "rfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 1 1 target 2
	ikrule "lfoot" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 1 1 target 3
	ikrule "ikclip" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 1 1 target 4
}

$IncludeModel "survivors/anim_TeenAngst.mdl"
$IncludeModel "survivors/gestures_TeenAngst.mdl"
$IncludeModel "survivors/anim_mechanic.mdl" // only
$IncludeModel "survivors/gestures_mechanic.mdl"
$IncludeModel "survivors/anim_NamVet.mdl" //---nonon--biker,manager,namvet


$IncludeModel "survivors/anim_gambler.mdl" // only
$IncludeModel "survivors/anim_producer.mdl" // only
$IncludeModel "survivors/anim_coach.mdl" // only