// by Starfelll
   
    $Include "../QC/Bill_namvet.qc"
    $ModelName "survivors/survivor_namvet.mdl"
    // $Include "../QC/Coach.qc"
    // $ModelName "survivors/survivor_coach.mdl"
    //$Include "../QC/Ellis_mechanic.qc"
    //$Include "../QC/Francis_biker.qc"
    //$Include "../QC/Louis_manager.qc"
    //$Include "../QC/Nick_gambler.qc"
    //$Include "../QC/Rochelle_producer.qc"
    //$Include "../QC/Zoey_teenangst.qc"

    $ModelName "test.mdl"